// AUTO-GENERADO por scripts/sync-data.py — no editar manualmente

export interface Episode {
  id: number
  title: string
  quote: string
  guest: string
  guestRole: string
  topics: string[]
  city: string
  country: string
  appleUrl: string
  spotifyUrl: string
  imageUrl: string
  guestImageUrl: string
  guestAvatarSeed: string
  featured: boolean
}

export interface TopicStat {
  name: string
  count: number
}

export const episodes: Episode[] = [
  {
    id: 104,
    title: "Resiliencia: una estrategia para las ciudades",
    quote: "",
    guest: "José Corral",
    guestRole: "Intendende de la ciudad de Santa Fe, Argentina 2011-2019",
    topics: ["Resiliencia", "Gobernanza"],
    city: "Santa Fe",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/us/podcast/resiliencia-una-estrategia-para-las-ciudades/id1093603743?i=1000526410232",
    spotifyUrl: "https://open.spotify.com/episode/75QjcwTgpOVZT0NVsdf8cI?si=U5qfwf82T0mpM3D0uxFb8Q",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Jose%20Corral.jpeg",
    guestAvatarSeed: "joscorral",
    featured: false,
  },
  {
    id: 103,
    title: "Procesos participativos en el diseño del transporte público",
    quote: "",
    guest: "Mercedes Vidal",
    guestRole: "ex Concejal de Movilidad y ex Presidenta de Transportes Metropolitanos de Barcelona",
    topics: ["Movilidad", "Gobernanza"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/us/podcast/procesos-participativos-en-el-dise%C3%B1o-del-transporte/id1093603743?i=1000501900029",
    spotifyUrl: "https://open.spotify.com/episode/2TuonhQCvlWxc8UtCijMLT?si=oMwJfeBhT1iF4sPbiH6Q4A",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Mercedes%20Vidal%20Lago.jpeg",
    guestAvatarSeed: "mercedesvidal",
    featured: false,
  },
  {
    id: 102,
    title: "Urbanismo ecosistémico",
    quote: "",
    guest: "Salvador Rueda",
    guestRole: "Ecólogo urbano. Fundador de la Agencia de Ecología Urbana, Barcelona.",
    topics: ["Urbanismo", "Espacio Público"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/us/podcast/urbanismo-ecosist%C3%A9mico/id1093603743?i=1000521171292",
    spotifyUrl: "https://open.spotify.com/episode/4sWYSykzdOhlW7OxDlbhb7?si=1c6xqdBcRDKUukphr2BWNA",
    imageUrl: "",
    guestImageUrl: "",
    guestAvatarSeed: "salvadorrueda",
    featured: false,
  },
  {
    id: 100,
    title: "Diplomacia urbana: el reto de ser influyente",
    quote: "",
    guest: "Alexis Roig",
    guestRole: "CEO of SciTech DiploHub and Barcelona’s Chief Science and Tech Envoy",
    topics: ["Internacionalización"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/us/podcast/diplomacia-urbana-el-reto-de-ser-influyente/id1093603743?i=1000463564865",
    spotifyUrl: "https://open.spotify.com/episode/0NdVik9CY7ZqpE2awkNeeG?si=L0oIuJvdQA6F-KzUTCOK8Q",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Alexis%20Roig.jpg",
    guestAvatarSeed: "alexisroig",
    featured: false,
  },
  {
    id: 98,
    title: "Cooperación Internacional: un aprendizaje compartido",
    quote: "",
    guest: "Dennis Quennet",
    guestRole: "Director de los Proyectos de Ciudades, Transporte e Industria sustentable de GIZ, cooperación alemana al desarrollo sustentable, en Mexico.",
    topics: ["Cooperación", "Internacionalización", "Movilidad"],
    city: "México",
    country: "México",
    appleUrl: "https://podcasts.apple.com/us/podcast/cooperaci%C3%B3n-internacional-un-aprendizaje-compartido/id1093603743?i=1000511337422",
    spotifyUrl: "https://open.spotify.com/episode/3KVEHX5HvkjuSh312uoKu6?si=PfZmahRER7CZvKL_D-46xA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Dennis%20Quennet.jpg",
    guestAvatarSeed: "dennisquennet",
    featured: false,
  },
  {
    id: 97,
    title: "Salud urbana: cómo la ciudad define nuestra calidad de vida",
    quote: "",
    guest: "Usama Bilal",
    guestRole: "Associate Professor of Epidemiology and Co-Director of the Urban Health Collaborative\nEpidemiology and Biostatistics, Drexel University, Philadelphia",
    topics: ["Salud", "Innovación"],
    city: "Philadelphia",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/us/podcast/salud-urbana-c%C3%B3mo-la-ciudad-define-nuestra-calidad-de-vida/id1093603743?i=1000761316362",
    spotifyUrl: "https://open.spotify.com/episode/7ucl4XdvFlJjH5quHWms9k?si=bsj2QFK-TgepZjKyJQqFDw",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Usama%20Bilal.png",
    guestAvatarSeed: "usamabilal",
    featured: false,
  },
  {
    id: 96,
    title: "Ecosistemas urbanos innovadores, Gov-Tech y talento",
    quote: "",
    guest: "Patricio Ovalle Woods",
    guestRole: "Senior Innovation Advisor | Expert in Entrepreneurship & Innovation Ecosystems, Providencia, Chile",
    topics: ["Innovación", "Gov-Tech"],
    city: "Chile",
    country: "Chile",
    appleUrl: "https://podcasts.apple.com/us/podcast/ecosistemas-urbanos-innovadores-gov-tech-y-talento/id1093603743?i=1000756742211",
    spotifyUrl: "https://open.spotify.com/episode/2uPljFpCx5JXOmM4eToiYF?si=hKMJQZfoS3C887xutXoFuw",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Patricio%20Ovalle%20Woods.png",
    guestAvatarSeed: "patricioovallewoods",
    featured: false,
  },
  {
    id: 95,
    title: "Ciudades, geopolítica y el nuevo (des) orden mundial",
    quote: "",
    guest: "Mariano Turzi",
    guestRole: "Dr en RRII, profesor Universidad Austral, Argentina",
    topics: ["Internacionalización", "Gobernanza"],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/us/podcast/ciudades-geopol%C3%ADtica-y-el-nuevo-des-orden-mundial/id1093603743?i=1000754009235",
    spotifyUrl: "https://open.spotify.com/episode/0TiewNr5ipqg2SU07vWMUl?si=6VnkOLFuSxmQgJPVDL4e1w",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Mariano%20Turzi.png",
    guestAvatarSeed: "marianoturzi",
    featured: false,
  },
  {
    id: 94,
    title: "Estonia, un país sin fronteras digitales",
    quote: "",
    guest: "Guillermo Chávez",
    guestRole: "Estonia e-Residency - Business Development Coordinator (Spain, Latin America)",
    topics: ["Smart Cities", "Gov-Tech"],
    city: "Guadalajara",
    country: "México",
    appleUrl: "https://podcasts.apple.com/us/podcast/estonia-un-pa%C3%ADs-sin-fronteras-digitales/id1093603743?i=1000753135947",
    spotifyUrl: "https://open.spotify.com/episode/3bpl5klGvyUjvwT60Z4TW5?si=U5IXdM9uSeOnWfJemeWnRg",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Guillermo%20Chavez%20Garc%C3%ADa.jpeg",
    guestAvatarSeed: "guillermochvez",
    featured: false,
  },
  {
    id: 93,
    title: "Buenos Aires: juegos, deporte y espacio urbano",
    quote: "",
    guest: "Samanta Szusterman",
    guestRole: "Diseñadora industrial, directora de Arquilúdica: estudio de diseño de espacios lúdicos, deportivos y de encuentro",
    topics: ["Espacio Público", "Urbanismo"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/us/podcast/buenos-aires-juegos-deporte-y-espacio-urbano/id1093603743?i=1000750039015",
    spotifyUrl: "https://open.spotify.com/episode/451DDoSSZLKTg4IxajSNGw?si=GZupnRnjR3SqpnQnh9RUrg",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Samanta%20Szusterman.jpeg",
    guestAvatarSeed: "samantaszusterman",
    featured: false,
  },
  {
    id: 92,
    title: "Urbanismo, una danza entre ciencia y arte",
    quote: "",
    guest: "Ramon Gras Alumà",
    guestRole: "Investigador en Ciencias de la Ciudad y Diseño Urbano, Universidad de Harvard, cofundador de Aretian",
    topics: ["Urbanismo"],
    city: "Miami",
    country: "España",
    appleUrl: "https://podcasts.apple.com/us/podcast/urbanismo-una-danza-entre-ciencia-y-arte/id1093603743?i=1000671222672",
    spotifyUrl: "https://open.spotify.com/episode/09n34hUOJ0Ar62MTAuApx2?si=t3W-9xvIQFSzE9mZPQ2WnQ",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Ramon%20Gras%20Alum%C3%A0.jpg",
    guestAvatarSeed: "ramongrasalum",
    featured: false,
  },
  {
    id: 91,
    title: "Silverstone, un evento, una ciudad",
    quote: "",
    guest: "Stephane Bazire",
    guestRole: "Director de Sostenibilidad de Silverstone, UK",
    topics: ["Sostenibilidad"],
    city: "Silverstone",
    country: "Reino Unido",
    appleUrl: "https://podcasts.apple.com/us/podcast/silverstone-un-evento-una-ciudad/id1093603743?i=1000669990311",
    spotifyUrl: "https://open.spotify.com/episode/4jjB5Qu9crR7j3E1f3tsdV?si=LLkcqiJERaWwV40HN3Z_BA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Stephane%20Bazire.png",
    guestAvatarSeed: "stephanebazire",
    featured: false,
  },
  {
    id: 90,
    title: "Mendoza, un oasis urbano",
    quote: "",
    guest: "Sebastián Fermani",
    guestRole: "Secretario de Ambiente y Desarrollo Urbano de la Ciudad de Mendoza, Argentina",
    topics: ["Sostenibilidad", "Urbanismo"],
    city: "Mendoza",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/us/podcast/mendoza-un-oasis-urbano/id1093603743?i=1000666946582",
    spotifyUrl: "https://open.spotify.com/episode/4sJBFL63ktIinG7yUl08wK?si=XSKrA6U7Tqq0VVLiGjPhOg",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Sebasti%C3%A1n%20Fermani.jpg",
    guestAvatarSeed: "sebastinfermani",
    featured: false,
  },
  {
    id: 89,
    title: "Impacto local de la acción global de las ciudades",
    quote: "En un mundo donde las ciudades concentran ya la mitad de la humanidad,\nla acción global de los gobiernos locales dejó de ser un lujo diplomático, es la palanca que conecta las agendas globales con las realidades de los ciudadanos, la que pone a una ciudad en el mapa de la cooperación y el financiamiento, y la que transforma la experiencia internacional en política pública de calidad.",
    guest: "Luz Amparo Medina",
    guestRole: "Consultora, socia de Phare Territorios Globales, Directora Distrital de Relaciones Internacionales de Bogotá (2020-24)",
    topics: ["Internacionalización"],
    city: "Guadalajara",
    country: "México",
    appleUrl: "https://podcasts.apple.com/us/podcast/impacto-local-de-la-acci%C3%B3n-global-de-las-ciudades/id1093603743?i=1000666048621",
    spotifyUrl: "https://open.spotify.com/episode/3GEJI67oSU9QANIzyrK1c1?si=8py6PmLIS7OktdF5IJndcQ",
    imageUrl: "/images/episodios/id%2089%20Luz%20Amparo%20Medina%20-%20Impacto%20local%20de%20la%20acci%C3%B3n%20global%20de%20las%20ciudades.png",
    guestImageUrl: "/images/INVITADOS/Luz%20Amparo%20Medina.jpg",
    guestAvatarSeed: "luzamparomedina",
    featured: false,
  },
  {
    id: 88,
    title: "De las estrategias a los cambios reales",
    quote: "",
    guest: "Xavi Matilla",
    guestRole: "Urbanista, profesor ETSAV-UPC. Arquitecte en Cap de Barcelona (2019-2023)",
    topics: ["Urbanismo", "Gobernanza"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/us/podcast/de-las-estrategias-a-los-cambios-reales/id1093603743?i=1000663958522",
    spotifyUrl: "https://open.spotify.com/episode/2MQlLEIBbRItptpnud4DRY?si=15ad593618824460",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Xavier%20Matilla.jpeg",
    guestAvatarSeed: "xavimatilla",
    featured: false,
  },
  {
    id: 87,
    title: "Smart City: Modelo Latam",
    quote: "",
    guest: "Diana Celis",
    guestRole: "Consultora en Proyectos de TIC, Ciudades y Territorios Inteligentes",
    topics: ["Smart Cities"],
    city: "Bogotá",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/us/podcast/smart-cities-el-modelo-latam/id1093603743?i=1000610928223",
    spotifyUrl: "https://open.spotify.com/episode/6NLH0YWOwvXdT8mhcvX4hf?si=kmEd_ekNRyqMkgtdgbJxPQ",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Diana%20Celis.jpeg",
    guestAvatarSeed: "dianacelis",
    featured: false,
  },
  {
    id: 86,
    title: "Tandil, un modelo inspirador",
    quote: "",
    guest: "Pedro Espondaburu",
    guestRole: "Docente Innovación y Desarrollo. Ciencias Económicas Unicen. Tandil, Argentina",
    topics: ["Innovación", "Desarrollo"],
    city: "Tandil",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/us/podcast/tandil-un-modelo-inspirador/id1093603743?i=1000611751709",
    spotifyUrl: "https://open.spotify.com/episode/0UwM9c3P8ns6iQsy6KXZn4?si=bHJ-BC06TkSoIamY_-lHCw",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Pedro%20Espondaburu.jpeg",
    guestAvatarSeed: "pedroespondaburu",
    featured: false,
  },
  {
    id: 85,
    title: "A la escuela en Bicibus!",
    quote: "",
    guest: "Mireia Piqueras",
    guestRole: "Vocal del proyecto Bicibus Barcelona",
    topics: ["Movilidad", "Bicicleta"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000583584745",
    spotifyUrl: "https://open.spotify.com/episode/3gruPqplDXneqNNqnPfne1?si=HRWrVxwwQOm97TnjoO0-PA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Mireia%20Piqueras.jpeg",
    guestAvatarSeed: "mireiapiqueras",
    featured: false,
  },
  {
    id: 84,
    title: "Ciudades globales en un mundo desglobalizado",
    quote: "Las grandes ciudades se están convirtiendo en focos de resistencia ante el autoritarismo y el nacionalismo excluyente. Cuando Estados Unidos salió de los acuerdos de París, Nueva York, Chicago y Los Ángeles se mantuvieron. Las capitales de Hungría, Polonia y Turquía contraponiendo la lógica de sus propios gobiernos. La reacción es muy urbana.",
    guest: "Agustí Fernández de Losada",
    guestRole: "Director del programa Ciudades Globales (CIDOB)",
    topics: ["Internacionalización"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudades-globales-en-un-mundo-desglobalizado/id1093603743?i=1000571151410",
    spotifyUrl: "https://open.spotify.com/episode/0xMm1L5RS0GTH84bEO5BHb?si=edc7bc4c55f64cd9",
    imageUrl: "/images/episodios/id%2084%20Agusti%20Fernandez%20de%20Losada%20-%20Ciudades%20Globales%20en%20un%20mundo%20desglobalizado.jpg",
    guestImageUrl: "/images/INVITADOS/Agusti%20Fernandez%20Losada.png",
    guestAvatarSeed: "agustfernndezdelosad",
    featured: true,
  },
  {
    id: 83,
    title: "La expansión urbana, una aliada de la biodiversidad.",
    quote: "",
    guest: "Nicolás Galarza",
    guestRole: "Viceministro de Ambiente de Colombia",
    topics: ["Sostenibilidad", "Urbanismo", "Equidad"],
    city: "Bogotá",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000567274033",
    spotifyUrl: "https://open.spotify.com/episode/3zYpHdC4okzY0n0eYVeQUQ?si=s-4aEX5JQSOs4ZF3jtHDqQ",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Nical%C3%A1s%20Galarza%20bw.jpeg",
    guestAvatarSeed: "nicolsgalarza",
    featured: false,
  },
  {
    id: 82,
    title: "Pinamar: la reinvención del mar",
    quote: "Hay ciudades que ganan dinero mientras se degradan. Pinamar era una de ellas: cinco intendentes destituidos por corrupción en siete años. Fue entonces cuando los vecinos eligieron a alguien de 29 años que nunca había gobernado nada. Lo que encontró no era solo una crisis institucional: era una ciudad que había dejado de creer en sí misma.",
    guest: "Martin Yeza",
    guestRole: "Intendente de Pinamar",
    topics: ["Gobernanza", "Urbanismo"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://open.spotify.com/episode/2PpNRwrTz4dhYO9YvdUsPf?si=50316716608f4314",
    spotifyUrl: "https://open.spotify.com/episode/2PpNRwrTz4dhYO9YvdUsPf?si=AgYrB_t-QYW08G1FP5X4JQ",
    imageUrl: "/images/episodios/id%2082%20Mart%C3%ADn%20Yeza%20-%20Pinamar%20la%20reinvenci%C3%B3n%20del%20mar.png",
    guestImageUrl: "/images/INVITADOS/martin%20yeza.jpeg",
    guestAvatarSeed: "martinyeza",
    featured: true,
  },
  {
    id: 81,
    title: "Alcaldes de la bicicleta: Madrid",
    quote: "",
    guest: "Fernando García",
    guestRole: "Alcalde de la Bici en Madrid",
    topics: ["Movilidad"],
    city: "Madrid",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000558173519",
    spotifyUrl: "https://open.spotify.com/episode/4DAdVvq3CUOKPH5GuXwwHf?si=8ef44125b0f34ae1",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Fernando%20Garcia.jpg",
    guestAvatarSeed: "fernandogarca",
    featured: false,
  },
  {
    id: 80,
    title: "El derecho a la ciudad",
    quote: "",
    guest: "Lorena Zárate",
    guestRole: "Founder Global Platform for the Right to the City",
    topics: ["Equidad"],
    city: "Ottawa",
    country: "Canada",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000555322146",
    spotifyUrl: "https://open.spotify.com/episode/1588LsqOMi6rWcKJ3iOqBb?si=6eafae54e0d6445c",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Lorena%20Zarate.jpg",
    guestAvatarSeed: "lorenazrate",
    featured: false,
  },
  {
    id: 79,
    title: "Desigualdad urbana, un reto del presente",
    quote: "",
    guest: "Edgardo Bilsky",
    guestRole: "Director de investigación del Secretariado Mundial de Ciudades y Gobiernos Locales Unidos (CGLU)",
    topics: ["Equidad", "Gobernanza"],
    city: "Guadalajara",
    country: "México",
    appleUrl: "https://podcasts.apple.com/us/podcast/desigualdad-urbana-un-reto-del-presente/id1093603743?i=1000554144936",
    spotifyUrl: "https://open.spotify.com/episode/1foxnB7UI2i8GZURNV7MFL?si=TfVyF7jDS92sOUtg-NoX8A",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Edgardo%20Bilsky.jpg",
    guestAvatarSeed: "edgardobilsky",
    featured: false,
  },
  {
    id: 78,
    title: "Data for public good in metropolitan areas",
    quote: "",
    guest: "Sarah Williams",
    guestRole: "Director of the Civic Data Design Lab @ MIT - Author: Data Action",
    topics: ["Datos", "Movilidad", "Urbanismo", "Innovación"],
    city: "Buenos Aires",
    country: "España",
    appleUrl: "https://podcasts.apple.com/us/podcast/data-for-public-good-in-metropolitan-areas/id1093603743?i=1000531225243",
    spotifyUrl: "https://open.spotify.com/episode/4QB2GcFmBTeMx2gUapfzOu?si=ba5ea84e7bb24ff1",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Sarah%20Williams.jpeg",
    guestAvatarSeed: "sarahwilliams",
    featured: false,
  },
  {
    id: 77,
    title: "Ciudadanía 3.0",
    quote: "",
    guest: "Javier Creus",
    guestRole: "Fundador & Director de estrategia de Ideas for Change",
    topics: ["Gobernanza", "Digitalización"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/us/podcast/ciudadanos-3-0/id1093603743?i=1000543315413",
    spotifyUrl: "https://open.spotify.com/episode/7nwVHZOwNI9eZZuv26jLxY?si=Vrf-jHONRzKhZNO-aG52BQ",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Javier%20Creus.jpeg",
    guestAvatarSeed: "javiercreus",
    featured: false,
  },
  {
    id: 76,
    title: "Ciudades cuidadoras",
    quote: "",
    guest: "Diana Maria Parra Romero",
    guestRole: "Subsecretaria de Politicas de Igualdad de Bogotá",
    topics: ["Equidad", "Gobernanza"],
    city: "Bogotá",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/us/podcast/bogot%C3%A1-una-ciudad-cuidadora/id1093603743?i=1000535344330",
    spotifyUrl: "https://open.spotify.com/episode/1dqU6pFBnhGbbn0zUihYrg?si=WD1AUwB_RiyI6h-wH0oAbQ",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Diana%20Maria%20Parra.jpeg",
    guestAvatarSeed: "dianamariaparraromer",
    featured: false,
  },
  {
    id: 75,
    title: "Boti: Una experiencia ciudadana",
    quote: "Los documentos hoy los centraliza el gobierno, pero son de las personas. La idea es que si un chico necesita una partida de nacimiento para anotarse en el colegio, no tenga que ir al registro civil, hacer la fila, y llevar un papel de una oficina de gobierno a otra. Si la partida está asociada a tu identidad digital, se la facilitamos en una carpeta y desde ahí la podés compartir.",
    guest: "Agustín Suárez",
    guestRole: "Subsecretario de Ciudad Inteligente",
    topics: ["Agricultura"],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/us/podcast/boti-una-experiencia-ciudadana/id1093603743?i=1000552154833",
    spotifyUrl: "https://open.spotify.com/episode/6Q7cWs225sNUpUiZZZc5y8?si=lAqsYByDTLypokzJIRkIFg",
    imageUrl: "/images/episodios/id%2075%20Agust%C3%ADn%20Su%C3%A1rez%20-%20Boti%20Una%20experiencia%20ciudadana.jpg",
    guestImageUrl: "/images/INVITADOS/Agust%C3%ADn%20Su%C3%A1rez.jpg",
    guestAvatarSeed: "agustnsurez",
    featured: true,
  },
  {
    id: 74,
    title: "Buenos Aires: Un elefante ágil",
    quote: "",
    guest: "Melisa Breda",
    guestRole: "Subsecretaria de Políticas Públicas basadas en Evidencia, Ciudad de Buenos Aires",
    topics: ["Gobernanza", "Innovación"],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000527175980",
    spotifyUrl: "https://www.spreaker.com/episode/45482121",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Melisa%20Breda.jpeg",
    guestAvatarSeed: "melisabreda",
    featured: false,
  },
  {
    id: 73,
    title: "Urbanistas: integradores en clave espacial",
    quote: "",
    guest: "Federico Bervejillo",
    guestRole: "Catedrático de Urbanismo, Ambiente y Paisaje de la Universidad ORT en Uruguay",
    topics: ["Urbanismo"],
    city: "Montevideo",
    country: "Uruguay",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000523565982",
    spotifyUrl: "https://open.spotify.com/episode/2BT8vECE0h3sFQoeiA02Nu?si=Dylg8ID4SPSa_n997DRrOA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Federico%20Bervejillo.jpg",
    guestAvatarSeed: "federicobervejillo",
    featured: false,
  },
  {
    id: 72,
    title: "La bici vino para quedarse",
    quote: "Cuando miras una sociedad, si miras cómo se mueve, te puede decir muchas pistas sobre cómo es esa sociedad. Cuando te subís a una bicicleta lo acabás entendiendo todo un poco. Es como que abrís los ojos a tu entorno, a tu vida, y empezás a desbloquear elementos que en tiempos de crisis climática y tantas malas noticias, uno necesitaba desbloquear.",
    guest: "Carles Benito",
    guestRole: "Presidente Bicicleta Club de Catalunya",
    topics: ["Movilidad", "Bicicleta"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/us/podcast/la-bici-vino-para-quedarse/id1093603743?i=1000519737149",
    spotifyUrl: "https://open.spotify.com/episode/43yWoqo8HKAM8SMbLb9nsF?si=WJlkhHv-RVqOkg3G1MOsfg",
    imageUrl: "/images/episodios/id%2072%20Carles%20Benito%20-%20La%20bici%20vino%20para%20quedarse.jpeg",
    guestImageUrl: "/images/INVITADOS/carles%20benito.png",
    guestAvatarSeed: "carlesbenito",
    featured: false,
  },
  {
    id: 71,
    title: "Metrópolis, el desafío de la escala humana",
    quote: "",
    guest: "Octavi de la Varga Mas",
    guestRole: "Metropolis Secretary General",
    topics: ["Movilidad", "Urbanismo"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/us/podcast/metrópolis-el-desaf%C3%ADo-de-la-escala-humana/id1093603743?i=1000516989505",
    spotifyUrl: "https://open.spotify.com/episode/5eD8VV5ZNJDXUUxCQEDyx7?si=j24Lm1W1TXufmd4hw2ymxQ",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Octavi%20de%20la%20Varga%20Mas.jpg",
    guestAvatarSeed: "octavidelavargamas",
    featured: false,
  },
  {
    id: 70,
    title: "Nuevos problemas, nuevas competencias",
    quote: "",
    guest: "Gabriel Lanfranchi",
    guestRole: "Director Ciudades CIPPEC",
    topics: ["Gobernanza", "Urbanismo"],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000443424811",
    spotifyUrl: "https://open.spotify.com/episode/5Rrcu8okMIQF7j10Nc1EDO?si=W4nHSCDOTkqx5e1TiG03gQ",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Gabriel%20Lanfranchi.png",
    guestAvatarSeed: "gabriellanfranchi",
    featured: false,
  },
  {
    id: 69,
    title: "City Prosperity Initiative, UN-Habitat",
    quote: "",
    guest: "Luis Herrera Favela",
    guestRole: "City Prosperity Initiative, UN-Habitat",
    topics: ["Internacionalización", "Urbanismo"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000507372571",
    spotifyUrl: "https://open.spotify.com/episode/0gj9tmYtCXM1bfpg5ExebE?si=PjOMnAoIQ6yOH-fmplYZ3g",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Luis%20Herrera%20Favela.jpg",
    guestAvatarSeed: "luisherrerafavela",
    featured: false,
  },
  {
    id: 68,
    title: "El Salvador: el cambio va de la mano de la tecnología",
    quote: "",
    guest: "Mónica Taher",
    guestRole: "Technological & Economic International Affairs at Trade & Investments Secretariat - El Salvador’s Government",
    topics: ["Smart Cities", "Gov-Tech"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000506524995",
    spotifyUrl: "https://open.spotify.com/episode/5NrpJkrxfpoJBRkimtxtbc?si=5MpniOKfSZSH0K8M4bf8pQ",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Monica%20Taher.jpeg",
    guestAvatarSeed: "mnicataher",
    featured: false,
  },
  {
    id: 67,
    title: "Israel, Start-Up Nation",
    quote: "",
    guest: "Sergio Vinitsky",
    guestRole: "Fundador Smart Cities Institute, Israel",
    topics: ["Smart Cities", "Innovación"],
    city: "Tel Aviv",
    country: "Israel",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000503802297",
    spotifyUrl: "https://open.spotify.com/episode/2tI1gLIBuvyMoRIHrZJE0X?si=FGBFrvc8TXOqXwz1hHxZcw",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Sergio%20Vinitsky.jpeg",
    guestAvatarSeed: "sergiovinitsky",
    featured: false,
  },
  {
    id: 66,
    title: "Urbanismo y salud: el Covid es un síntoma",
    quote: "",
    guest: "Elvis García",
    guestRole: "Doctor en Salud Pública. Harvard University",
    topics: ["Urbanismo", "Salud"],
    city: "Miami",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000482574229",
    spotifyUrl: "https://open.spotify.com/episode/5pn3fgwv4LPehFCk6irDe8?si=LenO0wlxRfyykYfbaF9gfA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Elvis%20Garcia.jpg",
    guestAvatarSeed: "elvisgarca",
    featured: false,
  },
  {
    id: 65,
    title: "La ciudad como proyecto",
    quote: "Para mí la ciudad más smart, más inteligente, es la que es la expresión de un proyecto colectivo de sus ciudadanos, sobre la que después utilizamos como gran instrumento la tecnología.",
    guest: "Jordi Hereu",
    guestRole: "Ex-Alcalde de Barcelona - CEO IdentiCity",
    topics: ["Gobernanza", "Urbanismo"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000407391334",
    spotifyUrl: "https://open.spotify.com/episode/1O9k9RJSb5ndxwJLXeT3ZA?si=A-cteR-7T4us74HRH-EXEQ",
    imageUrl: "/images/episodios/id%2065%20Jordi%20Hereu%20-%20La%20ciudad%20como%20proyecto.JPEG",
    guestImageUrl: "/images/INVITADOS/Jordi%20Hereu.jpeg",
    guestAvatarSeed: "jordihereu",
    featured: true,
  },
  {
    id: 64,
    title: "Privilegios ambientales, una nueva forma de desigualdad",
    quote: "",
    guest: "Isabelle Anguelovski",
    guestRole: "Directora del Barcelona Lab for Urban Environmental Justice and Sustainability",
    topics: ["Sostenibilidad", "Equidad", "Innovación"],
    city: "Madrid",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000452560984",
    spotifyUrl: "https://open.spotify.com/episode/6ER1GtySs7KSiLzFj7kG0g?si=pyZe0zEJQYqDmmjCOqcpPw",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Isabelle%20Anguelovski.jpeg",
    guestAvatarSeed: "isabelleanguelovski",
    featured: false,
  },
  {
    id: 63,
    title: "Supermanzanas: urbanismo para los ciudadanos",
    quote: "",
    guest: "Salvador Rueda",
    guestRole: "Ecólogo urbano. Fundador de la Agencia de Ecología Urbana, Barcelona.",
    topics: ["Sostenibilidad", "Urbanismo"],
    city: "Boston",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000426785691",
    spotifyUrl: "https://open.spotify.com/episode/0HsygrTj2vuW8iu5AZQiR4?si=WbIwOpHyR1mfcQHBQXMyBQ",
    imageUrl: "",
    guestImageUrl: "",
    guestAvatarSeed: "salvadorrueda",
    featured: false,
  },
  {
    id: 62,
    title: "La simbiosis industrial: nuevo paradigma económico",
    quote: "",
    guest: "Verónica Kuchinow",
    guestRole: "CEO SÍMBIOSY. Curadora del Circular Economy European Summit",
    topics: ["Sostenibilidad", "Innovación"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000372447037",
    spotifyUrl: "https://open.spotify.com/episode/1SqjZBVsNh1gHgSQSS218E?si=https://open.spotify.com/episode/1SqjZBVsNh1gHgSQSS218E?si=liIOKFXOQESjtiebWpAAqA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Ver%C3%B3nica%20Kuchinow.jpeg",
    guestAvatarSeed: "vernicakuchinow",
    featured: false,
  },
  {
    id: 61,
    title: "Mercados Urbanos: una tradición centenaria en las ciudades",
    quote: "",
    guest: "Genis Arnàs Páez",
    guestRole: "Director del servicio de mercados del Instituto Municipal de Mercados de Barcelona",
    topics: ["Espacio Público", "Mercados"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000397479938",
    spotifyUrl: "https://open.spotify.com/episode/3RUMmKQKEXsBbbzJ4mIWKQ?si=7a2_U90ZQLitFCOJz2cbzg",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Genis%20Arnas%20P%C3%A1ez.jpg",
    guestAvatarSeed: "genisarnspez",
    featured: false,
  },
  {
    id: 60,
    title: "Conexión de áreas metropolitanas, en bici",
    quote: "",
    guest: "Silvia Casorrán",
    guestRole: "Specialist Sustainable Mobility, head of bicycle projects Metropolitan Area of Barcelona",
    topics: ["Movilidad", "Urbanismo"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000412305094",
    spotifyUrl: "https://open.spotify.com/episode/0IqgenJIV0swhwcDiSbiZi?si=vZJP1ZgJQnK1jzJCc1eISg",
    imageUrl: "",
    guestImageUrl: "",
    guestAvatarSeed: "silviacasorrn",
    featured: false,
  },
  {
    id: 59,
    title: "Smart Cities: esto va de personas",
    quote: "",
    guest: "Josep Ferrer",
    guestRole: "Ex-Director de Smart City y CIO de Barcelona (2012-15), Director Desarrollo Internacional DOXA",
    topics: ["Smart Cities", "Internacionalización"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000377535590",
    spotifyUrl: "https://open.spotify.com/episode/3ahQufWmaJKAXNZgudvwda?si=icZ8lrQsTxmi2Mf1Vg1PhA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Josep%20Ferrer.jpg",
    guestAvatarSeed: "josepferrer",
    featured: false,
  },
  {
    id: 58,
    title: "Alimentación, salud y política urbana",
    quote: "Tendemos a pensar en el mundo rural cuando pensamos en las políticas alimentarias, porque allí se produce el alimento. Pero no podemos olvidar que donde se consume y se comercializa la mayor parte son las ciudades. Más de la mitad de la humanidad vive en ciudades. Si queremos transformar el modelo agroalimentario, no puede ocurrir si las ciudades no se implican.",
    guest: "Alvaro Porro González",
    guestRole: "Comisionado de Economía Social, Desarrollo Local y Política Alimentaria, Ajuntament de Barcelona",
    topics: ["Salud", "Innovación"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000466763821",
    spotifyUrl: "https://open.spotify.com/episode/5gA3TsP4fCOknlcik2fHTO?si=61FtpWprTU-_Bs8kWODwzA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Alvaro%20Porro%20Gonzalez.jpg",
    guestAvatarSeed: "alvaroporrogonzlez",
    featured: false,
  },
  {
    id: 57,
    title: "Ciudades Resilientes: estar en forma es la mejor defensa",
    quote: "",
    guest: "Esteban León",
    guestRole: "Coordinador del Programa de Resiliencia Urbana de UNHabitat",
    topics: ["Sostenibilidad", "Gobernanza"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000400805736",
    spotifyUrl: "https://open.spotify.com/episode/4zbEwwemnm2m1L2FZX3Ytg?si=33lpewcHTQq2d2IbK9laAA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Esteban%20Le%C3%B3n.jpg",
    guestAvatarSeed: "estebanlen",
    featured: false,
  },
  {
    id: 56,
    title: "Smart Cities: una visión global de un concepto en evolución",
    quote: "",
    guest: "Pilar Conesa",
    guestRole: "CEO de Anteverti - Curadora del SCEWC Barcelona",
    topics: ["Smart Cities"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000422228583",
    spotifyUrl: "https://open.spotify.com/episode/7lqyI9aKlOdVknTI9bjSkl?si=EDibtLolRrqr9j_jlOAmhQ",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Pilar%20Conesa.jpeg",
    guestAvatarSeed: "pilarconesa",
    featured: false,
  },
  {
    id: 55,
    title: "Bicicletas públicas",
    quote: "",
    guest: "Alvaro Nicolás",
    guestRole: "Asesor de la Regidora de Movilidad del Ayuntamiento de Barcelona",
    topics: ["Movilidad", "Bicicleta"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000370329334",
    spotifyUrl: "https://open.spotify.com/episode/6rojS0lPtV8xOQ1FLNOa4F?si=3uFJ5TJ6TASUEFQ5BrHELQ",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Alvaro%20Nicolas.jpeg",
    guestAvatarSeed: "alvaronicols",
    featured: false,
  },
  {
    id: 54,
    title: "Urbanismo feminista: visibilizando lo cotidiano",
    quote: "",
    guest: "Sara Ortiz",
    guestRole: "Urban Planner and Sociologist at Col·lectiu Punt 6 SCCL",
    topics: ["Urbanismo"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000456267503",
    spotifyUrl: "https://open.spotify.com/episode/3agxERa8JqWMt58gnFobAb?si=i1wU8IvgR2yHJuZbyXY-Dg",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Sara%20Ortiz.jpeg",
    guestAvatarSeed: "saraortiz",
    featured: false,
  },
  {
    id: 53,
    title: "Las ciudades tienen que reinventar la gestión",
    quote: "",
    guest: "Luis Gómez",
    guestRole: "Director de Sectores Estratégicos del Ayuntamiento de Barcelona",
    topics: ["Gobernanza"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000430009425",
    spotifyUrl: "https://open.spotify.com/episode/3re7QKcZoKB6sSHqfIpRHK?si=FN30RI_cS0WOcdBI5ac-bg",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Luis%20Gomez.jpeg",
    guestAvatarSeed: "luisgmez",
    featured: false,
  },
  {
    id: 52,
    title: "C40: red de ciudades para el desarrollo sostenible",
    quote: "",
    guest: "Mariola Panzuela",
    guestRole: "Transport Network Manager | C40 Cities",
    topics: ["Sostenibilidad", "Internacionalización"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000424333818",
    spotifyUrl: "https://open.spotify.com/episode/5BRuS1OrzozQwNf40S89H7?si=PBKsdRTFTa2mMk-7LkEpiA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Mariola%20Panzuela.jpeg",
    guestAvatarSeed: "mariolapanzuela",
    featured: false,
  },
  {
    id: 51,
    title: "Bikesharing: dos ruedas, dos modelos",
    quote: "",
    guest: "Miguel Rodríguez Planas",
    guestRole: "Manager -Public-Private Sector Research Center (PPSRC) de IESE",
    topics: ["Movilidad", "Bicicleta"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000444074888",
    spotifyUrl: "https://open.spotify.com/episode/6nkVuCX2uCsT1cofkms5pT?si=hZ8ZubAWQ3axlDM-bo9C9A",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Miquel_Rodriguez_Planas%20bw.png",
    guestAvatarSeed: "miguelrodrguezplanas",
    featured: false,
  },
  {
    id: 50,
    title: "La ciudad como solución: nueva agenda urbana",
    quote: "",
    guest: "Rosa Suriñach",
    guestRole: "Partnerships & Communications ONU Habitat",
    topics: ["Internacionalización", "Urbanismo"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000389710855",
    spotifyUrl: "https://open.spotify.com/episode/11PNrE1JmXGQEparJ4WTJY?si=fP6tlMxcTCmkFebTKjbeFw",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Rosa%20Suri%C3%B1ach.jpg",
    guestAvatarSeed: "rosasuriach",
    featured: false,
  },
  {
    id: 49,
    title: "Pasado, presente y futuro de las Smart Cities",
    quote: "",
    guest: "Ugo Valenti",
    guestRole: "Smart City Expo World Congress Director",
    topics: ["Smart Cities"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000390366026",
    spotifyUrl: "https://open.spotify.com/episode/6jOdeOCD0bJBDBKq7itjsi?si=NNqb7tNJQaOQVOPvD1hoFA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Ugo%20Valenti.jpg",
    guestAvatarSeed: "ugovalenti",
    featured: false,
  },
  {
    id: 48,
    title: "Siglo XXI, el siglo de las ciudades",
    quote: "",
    guest: "CiudadHub",
    guestRole: "Podcast de las Ciudades",
    topics: ["Urbanismo", "Internacionalización"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000364882952",
    spotifyUrl: "https://open.spotify.com/episode/4Z3VJD1qmQaLYPthXUsJGK?si=NmIPPON5T7iLvLzGUjkx8g",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/CiudadHub.png",
    guestAvatarSeed: "ciudadhub",
    featured: false,
  },
  {
    id: 47,
    title: "Ciudades inclusivas ¿Cómo gestionar la diversidad?",
    quote: "",
    guest: "Víctor Pineda",
    guestRole: "President of World ENABLED, Adjunct Professor, Univesity of California at Berkeley",
    topics: ["Equidad"],
    city: "Berkeley",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000414798619",
    spotifyUrl: "https://open.spotify.com/episode/6TGFZTuBCkQs0soRXYp4NJ?si=gIdZVGgeQ0mx72foaPZpRQ",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/V%C3%ADctor%20Pineda.jpg",
    guestAvatarSeed: "vctorpineda",
    featured: false,
  },
  {
    id: 46,
    title: "Ciudades: wikipedias urbanas",
    quote: "",
    guest: "Manu Fernández",
    guestRole: "Program Coordinator Smart City Expo international events",
    topics: ["Smart Cities"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000380554735",
    spotifyUrl: "https://open.spotify.com/episode/7prTMpO5Corlc5nsrzLYst?si=ddU2OuOxSK2rGuowhwVTVA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/ManuvFernandez%20bw.jpg",
    guestAvatarSeed: "manufernndez",
    featured: false,
  },
  {
    id: 45,
    title: "Bogotá, capital de la bicicleta",
    quote: "",
    guest: "David Uniman",
    guestRole: "Gerente de la Bicicleta de la Alcaldía de Bogotá (2015-19)",
    topics: ["Movilidad", "Bicicleta"],
    city: "Bogotá",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000429341002",
    spotifyUrl: "https://open.spotify.com/episode/5RuMC51tuOEx8QG5stCP29?si=KK-DNvP9SGCe_6eCk7tW5Q",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/David%20Uniman.jpeg",
    guestAvatarSeed: "daviduniman",
    featured: false,
  },
  {
    id: 44,
    title: "Seguridad vial, un tema de salud pública",
    quote: "",
    guest: "Johnny López",
    guestRole: "Coordinador de Bogotá del programa Bloomberg para la Seguridad Vial",
    topics: ["Salud", "Seguridad Vial"],
    city: "Bogotá",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000368683874",
    spotifyUrl: "https://open.spotify.com/episode/6Uclk36poNNNoMp4iwc2Uq?si=1HpAY4g3RmqNeJyLBEe0rg",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Johnny%20L%C3%B3pez.png",
    guestAvatarSeed: "johnnylpez",
    featured: false,
  },
  {
    id: 43,
    title: "Gentrificación en las ciudades",
    quote: "",
    guest: "Carlos Hernández Correa",
    guestRole: "Profesor Urbanismo - Universidad Pontificia Javeriana",
    topics: ["Urbanismo", "Gentrificación"],
    city: "Bogotá",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000382469617",
    spotifyUrl: "https://open.spotify.com/episode/6tNpPIlxQoTBxJ9LGVVhVA?si=V6WKAAMuSnGZo4oBC1hz9A",
    imageUrl: "/images/episodios/id%2043%20Carlos%20Hernandez%20Correa%20-%20Gentrificaci%C3%B3n%20en%20las%20ciudades.jpg",
    guestImageUrl: "/images/INVITADOS/Carlos%20Hernandez%20Correa.jpg",
    guestAvatarSeed: "carloshernndezcorrea",
    featured: false,
  },
  {
    id: 42,
    title: "En movilidad la solución está en compartir",
    quote: "",
    guest: "Darío Hidalgo",
    guestRole: "Director Ejecutivo de la Fundación Despacio",
    topics: ["Movilidad"],
    city: "Bogotá",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000433720209",
    spotifyUrl: "https://open.spotify.com/episode/4VobG5HwXT1PuXdpyphWPo?si=OUmaj-43R76MjNQm0L_O_g",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Dar%C3%ADo%20Hidalgo.png",
    guestAvatarSeed: "darohidalgo",
    featured: false,
  },
  {
    id: 41,
    title: "GovLab: ¿cómo gobernar a través de la tecnología?",
    quote: "",
    guest: "Victoria Alsina",
    guestRole: "Fellow en el Mossavar-Rahmani Center for Business and Government de la Harvard Kennedy School y Profesora de la Universitat Pompeu Fabra",
    topics: ["Smart Cities", "Movilidad", "Innovación", "Gov-Tech"],
    city: "Tucumán",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000402119482",
    spotifyUrl: "https://open.spotify.com/episode/3PCa5HNkBHcGKYHqpzYyoM?si=3pIPyhfYTkOZ8G7hAcC1yA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Victoria%20Alsina%20Burgues.jpeg",
    guestAvatarSeed: "victoriaalsina",
    featured: false,
  },
  {
    id: 40,
    title: "El espacio público, la piel de la democracia",
    quote: "",
    guest: "Iván Acevedo",
    guestRole: "Director del Taller Profesional de Arquitectura y Urbanismo del Gobierno de Bucaramanga.",
    topics: ["Urbanismo", "Gobernanza", "Espacio Público"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000420078713",
    spotifyUrl: "https://open.spotify.com/episode/071cpQ37kTdMfGmFBVOhvm?si=GvKgapgjR7Sd8Duh-eTqsA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Ivan%20Acevedo.jpeg",
    guestAvatarSeed: "ivnacevedo",
    featured: false,
  },
  {
    id: 39,
    title: "Urbanismo Metropolitano",
    quote: "",
    guest: "Gabriel Lanfranchi",
    guestRole: "Director Posgrado Urbanismo Metropolitano, UBA",
    topics: ["Movilidad", "Urbanismo"],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000517839087",
    spotifyUrl: "https://open.spotify.com/episode/6DUhk0MrBQEQsZ1QNRLYtJ?si=5jHI9Y6KRXWctXJw6unaiA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Gabriel%20Lanfranchi.png",
    guestAvatarSeed: "gabriellanfranchi",
    featured: false,
  },
  {
    id: 38,
    title: "Megalópolis y tribus: dos caras de las ciudades",
    quote: "",
    guest: "Fabio Quetglas",
    guestRole: "Abogado, Urbanista, Consultor en desarrollo territorial",
    topics: ["Movilidad"],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000384917427",
    spotifyUrl: "https://open.spotify.com/episode/2bjblHazONIz4iLrPLaMIp?si=-A6ODE7bTeemIKbfMxAhOg",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Fabio%20Quetglas.jpeg",
    guestAvatarSeed: "fabioquetglas",
    featured: false,
  },
  {
    id: 37,
    title: "Gobierno digital para no hacer esperar al ciudadano",
    quote: "",
    guest: "Daniel Abadie",
    guestRole: "Ex Subsecretario de Gobierno Digital, Argentina. Consultor Public Digital",
    topics: ["Smart Cities", "Gobernanza"],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000478848610",
    spotifyUrl: "https://open.spotify.com/episode/3cILK06IJXsyPRjICOTJ0B?si=NgOO7THBRnm4Hn-aJ8pGsQ",
    imageUrl: "/images/episodios/id%2037%20Daniel%20Abadie%20-%20Gobierno%20digital%20para%20no%20hacer%20esperar%20al%20ciudadano.jpeg",
    guestImageUrl: "/images/INVITADOS/Daniel%20Abadie.jpg",
    guestAvatarSeed: "danielabadie",
    featured: false,
  },
  {
    id: 36,
    title: "Ciudades y Universidad, una alianza inteligente",
    quote: "",
    guest: "Omar Quiroga",
    guestRole: "Director Centro de Ciudades Inteligentes, FCE Universidad de Buenos Aires",
    topics: ["Smart Cities"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000424604373",
    spotifyUrl: "https://open.spotify.com/episode/1I7W5ngODg3aUa4vzxNthr?si=fOVEAWC6TWquRQpPmtVEyg",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Omar%20Quiroga.jpg",
    guestAvatarSeed: "omarquiroga",
    featured: false,
  },
  {
    id: 35,
    title: "Aeropuertos: mini-ciudades",
    quote: "",
    guest: "Franco Rinaldi",
    guestRole: "Especialista en aviación. Auditor.",
    topics: ["Movilidad", "Urbanismo"],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000375136075",
    spotifyUrl: "https://open.spotify.com/episode/0ATjb9vWRwNoTCMCTVj10o?si=dSXpJ7iVSWidmGLqH1PcyQ",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Franco%20Rinaldi.png",
    guestAvatarSeed: "francorinaldi",
    featured: false,
  },
  {
    id: 34,
    title: "Caracas, Venezuela: cómo planificar en medio de la crisis",
    quote: "",
    guest: "Zulma Bolívar",
    guestRole: "Presidente en Instituto Metropolitano de Urbanismo Taller Caracas",
    topics: ["Movilidad", "Urbanismo"],
    city: "Caracas",
    country: "Venezuela",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000380054059",
    spotifyUrl: "https://open.spotify.com/episode/3WLObjkec4EcvOq2A1JrgS?si=EeNM16p6QUG-cv513d3r_g",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Zulma%20Bolivar.png",
    guestAvatarSeed: "zulmabolvar",
    featured: false,
  },
  {
    id: 33,
    title: "Caminabilidad, la magia de redescubrir la ciudad",
    quote: "",
    guest: "Carolina Huffman",
    guestRole: "Fundadora Urbanismo Vivo",
    topics: ["Urbanismo", "Movilidad"],
    city: "Córdoba",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000422759182",
    spotifyUrl: "https://open.spotify.com/episode/3KdrD4SjPAYMuajZTnl5DP?si=hfQIRsYlTP2KQEiIYyvv8w",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Carolina%20Huffman.jpg",
    guestAvatarSeed: "carolinahuffman",
    featured: false,
  },
  {
    id: 32,
    title: "Placemaking: transformando espacios públicos en lugares",
    quote: "",
    guest: "Guillermo Bernal",
    guestRole: "Coordinador de Placemaking Latinoamérica, Fellow de Project for Public Spaces",
    topics: ["Espacio Público", "Urbanismo"],
    city: "Barcelona",
    country: "México",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000421743124",
    spotifyUrl: "https://open.spotify.com/episode/2V8mOezyRCmssIuBbm1PJa?si=rK1BT3yZQ6qb424qZFt6jg",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Guillermo%20Bernal.png",
    guestAvatarSeed: "guillermobernal",
    featured: false,
  },
  {
    id: 31,
    title: "Parques urbanos: mucho más que el pulmón de las ciudades",
    quote: "",
    guest: "Luis Romhan Diez",
    guestRole: "Director general Asociación Nacional de Parques de México",
    topics: ["Espacio Público"],
    city: "Guadalajara",
    country: "México",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000392500408",
    spotifyUrl: "https://open.spotify.com/episode/26eHPCX9WqvXWnOC8U45Sc?si=-0GY4tRZTYGYS5rmquKiQQ",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Luis%20Romhan%20Diez.jpeg",
    guestAvatarSeed: "luisromhandiez",
    featured: false,
  },
  {
    id: 30,
    title: "Lima cómo vamos: los ciudadanos evalúan su ciudad",
    quote: "",
    guest: "Patricia Alalta",
    guestRole: "Directora \"Lima Cómo Vamos?\"",
    topics: ["Gobernanza", "Internacionalización"],
    city: "Lima",
    country: "Perú",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000394443714",
    spotifyUrl: "https://open.spotify.com/episode/6xbZ22ATYnb0EonTqsFm1J?si=Hsg9xGQJRh-SJWrcE7bqkA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Patricia%20Alata%20bw.jpg",
    guestAvatarSeed: "patriciaalalta",
    featured: false,
  },
  {
    id: 29,
    title: "Medellín ante los desafíos de su éxito",
    quote: "",
    guest: "Jorge Pérez Jaramillo",
    guestRole: "Ex-Director de Planeación de Medellín (2012-15) / Lee Kuan Yew World City Prize",
    topics: ["Urbanismo", "Gobernanza"],
    city: "Oxford",
    country: "Reino Unido",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000384618088",
    spotifyUrl: "https://open.spotify.com/episode/2yhYNSH1ieoxhGtlwQtTw4?si=JVR6JMLLTqS8JkQ-0klzzw",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/JorgePerez%20bw.jpg",
    guestAvatarSeed: "jorgeprezjaramillo",
    featured: false,
  },
  {
    id: 28,
    title: "Londres: el transporte urbano como actividad vital",
    quote: "",
    guest: "Claudia Peñaranda",
    guestRole: "Principal City Planner at Transport for London.",
    topics: ["Movilidad"],
    city: "Londres",
    country: "Reino Unido",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000406474711",
    spotifyUrl: "https://open.spotify.com/episode/6cKohK8PmEcJpDw3vvpeWP?si=HgZSYjKaQoKv8xP3TD7Ivg",
    imageUrl: "/images/episodios/id%2028%20Claudia%20Pe%C3%B1aranda%20%20Londres%20el%20transporte%20urbano%20como%20actividad%20vital.jpeg",
    guestImageUrl: "/images/INVITADOS/Claudia%20Penaranda.jpeg",
    guestAvatarSeed: "claudiapearanda",
    featured: false,
  },
  {
    id: 27,
    title: "De las ciudades a los territorios: el modelo diamante",
    quote: "",
    guest: "Ignacio Alcalde",
    guestRole: "Experto Smart Cities & Territorios Inteligentes",
    topics: ["Smart Cities"],
    city: "Madrid",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000377671173",
    spotifyUrl: "https://open.spotify.com/episode/42YdiNJb7QKxZkiqUNZYFu?si=g6jQxmq0Q_iga6Ujf-VCCw",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Ignacio%20Alcalde.jpeg",
    guestAvatarSeed: "ignacioalcalde",
    featured: false,
  },
  {
    id: 26,
    title: "De las autopistas urbanas a las calles peatonales",
    quote: "Hay una foto del antes y después de la Gran Vía que dio la vuelta al mundo en las navidades de 2016. Nadie se daba cuenta de que aquello era un mar de vehículos, incluso los domingos. El urbanismo táctico no solo convenció de que el proyecto era importante para la ciudad, también demostró que era posible convencer a la ciudadanía de lo que en cuatro legislaturas nadie se había atrevido a hacer.",
    guest: "Carlos Corral",
    guestRole: "Ex subdirector de planificación de movilidad sostenible del Ayuntamiento de Madrid",
    topics: ["Movilidad", "Urbanismo"],
    city: "Madrid",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000446488585",
    spotifyUrl: "https://open.spotify.com/episode/2LzwWYO7grdTJHgICOtw0z?si=LnAlYomMRn-vEoA9k5mccA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Carlos%20Corral.png",
    guestAvatarSeed: "carloscorral",
    featured: true,
  },
  {
    id: 25,
    title: "Reputación, el storydoing-telling de las ciudades",
    quote: "",
    guest: "Pau Solanilla Franco",
    guestRole: "Consultor Internacional, autor de La República de la Reputación",
    topics: ["Internacionalización"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000471285168",
    spotifyUrl: "https://open.spotify.com/episode/3KKZ2VoTRmza7uVEjXov7P?si=3O73Ikn9R3mYcF3XJ1y1xw",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Pau%20Solanilla.jpeg",
    guestAvatarSeed: "pausolanillafranco",
    featured: false,
  },
  {
    id: 24,
    title: "Liderazgo colaborativo, la clave del desarrollo local",
    quote: "Las autoridades locales tienen el problema de que son las que están frente al ciudadano. El gobierno nacional está muy lejos. Mi receta es conseguir que la política, la empresa, la academia y las organizaciones sociales sean capaces de ir juntas a la autoridad superior con un mismo proyecto. Difícilmente esa autoridad se va a negar.",
    guest: "Alain Jorda",
    guestRole: "Experto en Desarrollo Local y Territorial",
    topics: ["Gobernanza", "Innovación"],
    city: "Manresa",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000440101551",
    spotifyUrl: "https://open.spotify.com/episode/3HAwZnmuNX6QNViUJOaEC8?si=0AX-E7PUSlSwQNyH0VbwYg",
    imageUrl: "/images/episodios/id%2024%20Alain%20Jorda%20-%20%20Liderazgo%20colaborativo%2C%20la%20clave%20del%20desarrollo%20local.jpeg",
    guestImageUrl: "/images/INVITADOS/Alain%20Jorda.png",
    guestAvatarSeed: "alainjorda",
    featured: true,
  },
  {
    id: 23,
    title: "¿Cómo enfrentar la rápida urbanización y el cambio climático?",
    quote: "",
    guest: "Ellis Juan",
    guestRole: "Ex-Director Iniciativa Ciudades Emergentes y Sostenibles (BID)",
    topics: ["Sostenibilidad"],
    city: "Miami",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000398690656",
    spotifyUrl: "https://open.spotify.com/episode/6wUIjS1kacDiij6d6sXrHK?si=AVu1JN_vRSSAIqBU5iVE3A",
    imageUrl: "",
    guestImageUrl: "",
    guestAvatarSeed: "ellisjuan",
    featured: false,
  },
  {
    id: 22,
    title: "Digitalización de las ciudades",
    quote: "",
    guest: "Pedro Julio Uribe Bermudez",
    guestRole: "Director Regional de Microsoft para Latinoamérica y el Caribe - Latin America & The Caribbean at Microsoft",
    topics: ["Smart Cities", "Gov-Tech"],
    city: "Miami",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000430529167",
    spotifyUrl: "https://open.spotify.com/episode/6yvb4gbZnkGG6nIiliAF9K?si=aQBbU--GSGG3XT4gHKcW-A",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Pedro%20Julio%20Uribe%20Bermudez.jpg",
    guestAvatarSeed: "pedrojuliouribebermu",
    featured: false,
  },
  {
    id: 21,
    title: "Nuevos sistemas de pago para la movilidad urbana",
    quote: "Cuando hablamos de movilidad urbana, nosotros somos una pieza: somos el pago dentro de este proceso. No podemos ir por separado. Existe una creciente demanda de gobiernos y ciudadanos que exigen ciudades más sostenibles, más conectadas, más seguras, más inclusivas. Y todos los actores —gobiernos, proveedores tecnológicos, universidades, startups, fintechs— tenemos que coexistir y trabajar conjuntamente.",
    guest: "Aida Esteban Millet",
    guestRole: "Senior Director, Urban Mobility and Smart Cities for LAC at Visa",
    topics: ["Smart Cities", "Movilidad"],
    city: "Miami",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000477227309",
    spotifyUrl: "https://open.spotify.com/episode/1EOQ9OagqobqA3vT4yIv63?si=Y5CcM9V-Qo-CTt6VpYA86Q",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Aida%20Esteban%20Millat.jpeg",
    guestAvatarSeed: "aidaestebanmillet",
    featured: false,
  },
  {
    id: 20,
    title: "CiudadesR: cómo devolver el río a las ciudades",
    quote: "Los ríos poco a poco fueron perdiendo importancia y se convirtieron en las cloacas de las ciudades: industria en sus bordes, aguas residuales, residuos de todo tipo. Pero hoy comenzamos a ver cómo los ríos pueden ser instrumentos muy poderosos dentro de la ciudad. Son conectores de casi todas las variables: espacio público, mezcla de usos, innovación, competitividad.",
    guest: "Carlos Eduardo Correa",
    guestRole: "Ex Alcalde de Montería y Alto Consejero para las Regiones de la Presidencia de Colombia",
    topics: ["Sostenibilidad", "Espacio Público"],
    city: "Montería",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000385312004",
    spotifyUrl: "https://open.spotify.com/episode/3g36zBXMxD61yCE6wl1o0j?si=dC7mUsIQRNyGGdTYm8P7Ng",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Carlos%20Eduardo%20Correa.jpg",
    guestAvatarSeed: "carloseduardocorrea",
    featured: true,
  },
  {
    id: 19,
    title: "Montevideo: laboratorio urbano",
    quote: "",
    guest: "Cristina Zubillaga",
    guestRole: "Directora de Desarrollo Sostenible e Inteligente de la Intendencia de Montevideo",
    topics: ["Innovación"],
    city: "Montevideo",
    country: "Uruguay",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000376736957",
    spotifyUrl: "https://open.spotify.com/episode/3ahQufWmaJKAXNZgudvwda?si=icZ8lrQsTxmi2Mf1Vg1PhA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Cristina%20Zubillaga.jpg",
    guestAvatarSeed: "cristinazubillaga",
    featured: false,
  },
  {
    id: 18,
    title: "Wonder Innovation Lab: las ciudades como experimento",
    quote: "",
    guest: "Carolina Pozo",
    guestRole: "Cofundadora Wonder Lab",
    topics: ["Innovación"],
    city: "New York",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000394443713",
    spotifyUrl: "https://open.spotify.com/episode/5N0pcHdk8tFfBw7H4zzeUJ?si=BIsCy5g6QTKXTQTmdIGG4Q",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Carolina%20Pozo.jpg",
    guestAvatarSeed: "carolinapozo",
    featured: false,
  },
  {
    id: 17,
    title: "Economía popular, ciudades y tecnología",
    quote: "",
    guest: "Mercedes Bidart",
    guestRole: "Fellow NYC Mayor's Office, MIT Master in City Planning, QUIPU co-founder",
    topics: ["Smart Cities"],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000448958913",
    spotifyUrl: "https://open.spotify.com/episode/0aGXhj45fTDM6vvlGdWV1r?si=4reqQ5IhT0yrqCe8owGwRQ",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Mercedes%20Bidart.jpg",
    guestAvatarSeed: "mercedesbidart",
    featured: false,
  },
  {
    id: 16,
    title: "Social Bicycle: movilidad medida en byts",
    quote: "",
    guest: "Daniel Treviño",
    guestRole: "Project Manager de Social Bicycle",
    topics: ["Movilidad", "Bicicleta"],
    city: "New York",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000371747782",
    spotifyUrl: "https://open.spotify.com/episode/4sSizDinbkUane7Hruy2SY?si=xUzuy2CvTlOt4gS46ld7fg",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Daniel%20Trevi%C3%B1o.jpg",
    guestAvatarSeed: "danieltrevio",
    featured: false,
  },
  {
    id: 15,
    title: "NYC, el bus también existe!",
    quote: "",
    guest: "Julián Bautista Rojas",
    guestRole: "Planificador Principal de Transporte en MTA Bus Company - Nueva York",
    topics: ["Movilidad"],
    city: "Zaragoza",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000420668860",
    spotifyUrl: "https://open.spotify.com/episode/3wxJHepvp7BvmpgKsVkkXM?si=iWfRYLONSKiSGiHarYm4hg",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Juli%C3%A1n%20Bautista%20Rojas.jpg",
    guestAvatarSeed: "julinbautistarojas",
    featured: false,
  },
  {
    id: 14,
    title: "Vehículos eléctricos: pasado, presente y futuro",
    quote: "",
    guest: "CiudadHub",
    guestRole: "Podcast de las Ciudades",
    topics: ["Movilidad", "Electrificación"],
    city: "Ottawa",
    country: "Canada",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000368131447",
    spotifyUrl: "https://open.spotify.com/episode/7kgPcvht4UpTfjdbDQ5Tfd?si=b06J7RIeQFSMGjaFIuB43w",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/CiudadHub.png",
    guestAvatarSeed: "ciudadhub",
    featured: false,
  },
  {
    id: 13,
    title: "Portland: una atípica ciudad estadounidense",
    quote: "",
    guest: "Mauricio Leclerc",
    guestRole: "Transportation Planning Section Manager - Portland, Oregon",
    topics: ["Movilidad", "Urbanismo"],
    city: "Portland",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000403022231",
    spotifyUrl: "https://open.spotify.com/episode/5x0oBfs58K3rphi0ZVHam5?si=5DBx0eUoRiK_G-8HGNiEww",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Mauricio%20Leclerq%20bw.jpg",
    guestAvatarSeed: "mauricioleclerc",
    featured: false,
  },
  {
    id: 12,
    title: "Hacker activismo urbano",
    quote: "",
    guest: "Leonardo Brawl",
    guestRole: "TransLAB.URB - Co-Founder",
    topics: ["Innovación"],
    city: "Porto Alegre",
    country: "Brasil",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000423195098",
    spotifyUrl: "https://open.spotify.com/episode/0i2DkzeKNj6S9N59M5ldYd?si=pV091p7mQK68AJhvUFhY2A",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Leonardo%20Brawl.jpeg",
    guestAvatarSeed: "leonardobrawl",
    featured: false,
  },
  {
    id: 11,
    title: "SmartCity Expo Latam: la experiencia latinoamericana",
    quote: "",
    guest: "Manuel Redondo",
    guestRole: "Director Smart City Expo Latam",
    topics: ["Smart Cities"],
    city: "Bilbao",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000395387019",
    spotifyUrl: "https://open.spotify.com/episode/3CGGU8qPX3KB1g0iZrXAzO?si=eITVmriLSgCxWT0031c-8A",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Manuel%20Redondo.jpg",
    guestAvatarSeed: "manuelredondo",
    featured: false,
  },
  {
    id: 10,
    title: "La implementación de la nueva agenda urbana - WUF9 Kuala Lumpur",
    quote: "",
    guest: "Elkin Velasquez",
    guestRole: "Director ONUHabitat Latinoamérica y el Caribe",
    topics: ["Internacionalización", "Urbanismo"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000404429488",
    spotifyUrl: "https://open.spotify.com/episode/3LKvaPrpOR5x7wuAZCGQdp?si=4lhxti-eQ2qqBu74AoLxUg",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Elkin%20Velazques%20bw.jpg",
    guestAvatarSeed: "elkinvelasquez",
    featured: false,
  },
  {
    id: 9,
    title: "El Malestar en las ciudades",
    quote: "",
    guest: "Elkin Velasquez",
    guestRole: "Director ONUHabitat Latinoamérica y el Caribe",
    topics: ["Urbanismo", "Equidad"],
    city: "Rio de Janeiro",
    country: "Brasil",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000460870405",
    spotifyUrl: "https://open.spotify.com/episode/54kxLwjThkwS4kI9UeHhzx?si=T6REzC3NQD2j-HEVYyuP_Q",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Elkin%20Velazques%20bw.jpg",
    guestAvatarSeed: "elkinvelasquez",
    featured: false,
  },
  {
    id: 8,
    title: "Ciudades 880, para los de 8 y los de 80",
    quote: "",
    guest: "Guillermo Peñalosa",
    guestRole: "Fundador y presidente de Ciudades 8 80",
    topics: ["Espacio Público", "Equidad"],
    city: "Toronto",
    country: "Canada",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000408860992",
    spotifyUrl: "https://open.spotify.com/episode/77oQtFWpwU8ybMPLY3r7mk?si=PMwOgL1XQ522FpFhpFq0Lg",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Guillermo%20Gil%20Pe%C3%B1aloza.jpeg",
    guestAvatarSeed: "guillermopealosa",
    featured: false,
  },
  {
    id: 7,
    title: "Las ciudades son \"cosa de niños\"",
    quote: "",
    guest: "Verónica Mansilla",
    guestRole: "Arquitecta fundadora del Estudio Trecediecinueve",
    topics: ["Urbanismo", "Equidad"],
    city: "Philadelphia",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000425048218",
    spotifyUrl: "https://open.spotify.com/episode/0kLbHUKsjhfBfziEuwFlDw?si=F1Dyd9UsTxSC5uhj4fN2tA",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Ver%C3%B3nica%20Mansilla.jpeg",
    guestAvatarSeed: "vernicamansilla",
    featured: false,
  },
  {
    id: 6,
    title: "En las ciudades, experimentar no es improvisar",
    quote: "",
    guest: "Jordi Honey-Roses",
    guestRole: "Assistant Professor at the School of Community and Regional Planning, University of British Columbia",
    topics: ["Urbanismo", "Innovación"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000450957597",
    spotifyUrl: "https://open.spotify.com/episode/6S9r9XB3luPtZdVcb29yn3?si=vpw7_Of2TYy70b2dzre_Aw",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Jordi%20Honeyroses.jpg",
    guestAvatarSeed: "jordihoneyroses",
    featured: false,
  },
  {
    id: 5,
    title: "Waterproofing data",
    quote: "",
    guest: "Joao Porto de Albuquereque",
    guestRole: "Director, Institute for Global Sustainable Development, University of Warwick",
    topics: ["Datos", "Gov-Tech"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000468470173",
    spotifyUrl: "https://open.spotify.com/episode/1tO3ZccyHfDhGwiaHgDPfy?si=MspJAZTjQJK5sWqknL5okw",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Joao%20Porto%20de%20Albuquerque.png",
    guestAvatarSeed: "joaoportodealbuquere",
    featured: false,
  },
  {
    id: 4,
    title: "Big data y urbanismo: lo importante son las preguntas",
    quote: "",
    guest: "Nancy Lozano",
    guestRole: "Economista Senior Banco Mundial",
    topics: ["Datos", "Urbanismo"],
    city: "San Salvador",
    country: "El Salvador",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000465633344",
    spotifyUrl: "https://open.spotify.com/episode/0nSCEfBLhdGEIwqYejFc7X?si=1JkctXS2Rn28h9VYkaA2mQ",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Nancy%20Lozano.png",
    guestAvatarSeed: "nancylozano",
    featured: false,
  },
  {
    id: 3,
    title: "Ir más despacio para llegar antes",
    quote: "",
    guest: "Carlos Pardo",
    guestRole: "Senior Manager - Pilots at NUMO -New Urban Mobility Alliance",
    topics: ["Movilidad", "Sostenibilidad"],
    city: "Washington",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000440992766",
    spotifyUrl: "https://open.spotify.com/episode/4cVnj89Sz5k6GMNvy9seXH?si=_ECPF-daSACE1l_np5RbrQ",
    imageUrl: "",
    guestImageUrl: "",
    guestAvatarSeed: "carlospardo",
    featured: false,
  },
  {
    id: 2,
    title: "Del transporte público colectivo a las plataformas de movilidad",
    quote: "",
    guest: "Juan Ortiz",
    guestRole: "Director del Consorcio de Transportes de Zaragoza",
    topics: ["Movilidad"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000391320970",
    spotifyUrl: "https://open.spotify.com/episode/121bmQ3T8lnOp85lFAeQre?si=9fERZqT5QV2d_qSI3NDG_A",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Juan%20Ortiz%20Taboada.jpg",
    guestAvatarSeed: "juanortiz",
    featured: false,
  },
  {
    id: 1,
    title: "CDMX: escuchar y compartir, una estrategia de inserción internacional",
    quote: "",
    guest: "Mariana Flores Mayen",
    guestRole: "Directora Ejecutiva de Representación Institucional CDMX",
    topics: ["Internacionalización"],
    city: "Puebla",
    country: "México",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000475488505",
    spotifyUrl: "https://open.spotify.com/episode/10TOlsvfqhHOkCL9aWssPs?si=zkfaJEmIRjC3qXHM_euwQQ",
    imageUrl: "",
    guestImageUrl: "/images/INVITADOS/Mariana%20Flores%20Mayen.jpg",
    guestAvatarSeed: "marianafloresmayen",
    featured: false,
  },
]

export const allTopics: TopicStat[] = [
  { name: "Urbanismo", count: 34 },
  { name: "Movilidad", count: 27 },
  { name: "Gobernanza", count: 18 },
  { name: "Smart Cities", count: 16 },
  { name: "Innovación", count: 15 },
  { name: "Internacionalización", count: 14 },
  { name: "Sostenibilidad", count: 11 },
  { name: "Equidad", count: 9 },
  { name: "Espacio Público", count: 8 },
  { name: "Gov-Tech", count: 6 },
  { name: "Bicicleta", count: 6 },
  { name: "Salud", count: 4 },
  { name: "Datos", count: 3 },
  { name: "Resiliencia", count: 1 },
  { name: "Cooperación", count: 1 },
  { name: "Desarrollo", count: 1 },
  { name: "Digitalización", count: 1 },
  { name: "Agricultura", count: 1 },
  { name: "Mercados", count: 1 },
  { name: "Seguridad Vial", count: 1 },
  { name: "Gentrificación", count: 1 },
  { name: "Electrificación", count: 1 },
]

export const allGuests = episodes.map(ep => ({
  name: ep.guest,
  role: ep.guestRole,
  city: ep.city,
  topics: ep.topics,
  episodeId: ep.id,
  episodeTitle: ep.title,
  appleUrl: ep.appleUrl,
  spotifyUrl: ep.spotifyUrl,
  guestAvatarSeed: ep.guestAvatarSeed,
}))
