// AUTO-GENERADO por scripts/sync-data.py — no editar manualmente

export interface Episode {
  id: number
  title: string
  description: string
  guest: string
  guestRole: string
  topics: string[]
  city: string
  country: string
  appleUrl: string
  spotifyUrl: string
  imageUrl: string
  guestAvatarSeed: string
}

export interface TopicStat {
  name: string
  count: number
}

export const episodes: Episode[] = [
  {
    id: 97,
    title: "Salud urbana: cómo la ciudad define nuestra calidad de vida",
    description: "",
    guest: "Usama Bilal",
    guestRole: "Associate Professor of Epidemiology and Co-Director of the Urban Health Collaborative\nEpidemiology and Biostatistics, Drexel University, Philadelphia",
    topics: ["Salud", "Innovación"],
    city: "Philadelphia",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/us/podcast/salud-urbana-c%C3%B3mo-la-ciudad-define-nuestra-calidad-de-vida/id1093603743?i=1000761316362",
    spotifyUrl: "https://open.spotify.com/episode/7ucl4XdvFlJjH5quHWms9k?si=bsj2QFK-TgepZjKyJQqFDw",
    imageUrl: "",
    guestAvatarSeed: "usamabilal",
  },
  {
    id: 96,
    title: "Ecosistemas urbanos innovadores, Gov-Tech y talento",
    description: "",
    guest: "Patricio Ovalle Woods",
    guestRole: "Senior Innovation Advisor | Expert in Entrepreneurship & Innovation Ecosystems, Providencia, Chile",
    topics: ["Innovación"],
    city: "Chile",
    country: "Chile",
    appleUrl: "https://podcasts.apple.com/us/podcast/ecosistemas-urbanos-innovadores-gov-tech-y-talento/id1093603743?i=1000756742211",
    spotifyUrl: "https://open.spotify.com/episode/2uPljFpCx5JXOmM4eToiYF?si=hKMJQZfoS3C887xutXoFuw",
    imageUrl: "",
    guestAvatarSeed: "patricioovallewoods",
  },
  {
    id: 95,
    title: "Ciudades, geopolítica y el nuevo (des) orden mundial",
    description: "",
    guest: "Mariano Turzi",
    guestRole: "Dr en RRII, profesor Universidad Austral, Argentina",
    topics: [],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/us/podcast/ciudades-geopol%C3%ADtica-y-el-nuevo-des-orden-mundial/id1093603743?i=1000754009235",
    spotifyUrl: "https://open.spotify.com/episode/0TiewNr5ipqg2SU07vWMUl?si=6VnkOLFuSxmQgJPVDL4e1w",
    imageUrl: "",
    guestAvatarSeed: "marianoturzi",
  },
  {
    id: 94,
    title: "Estonia, un país sin fronteras digitales",
    description: "",
    guest: "Guillermo Chávez",
    guestRole: "Estonia e-Residency - Business Development Coordinator (Spain, Latin America)",
    topics: ["Smart Cities", "Movilidad"],
    city: "Estonia",
    country: "Estonia",
    appleUrl: "https://podcasts.apple.com/us/podcast/estonia-un-pa%C3%ADs-sin-fronteras-digitales/id1093603743?i=1000753135947",
    spotifyUrl: "https://open.spotify.com/episode/3bpl5klGvyUjvwT60Z4TW5?si=U5IXdM9uSeOnWfJemeWnRg",
    imageUrl: "",
    guestAvatarSeed: "guillermochvez",
  },
  {
    id: 93,
    title: "Buenos Aires: juegos, deporte y espacio urbano",
    description: "",
    guest: "Samanta Szusterman",
    guestRole: "Diseñadora industrial, directora de Arquilúdica: estudio de diseño de espacios lúdicos, deportivos y de encuentro",
    topics: [],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/us/podcast/buenos-aires-juegos-deporte-y-espacio-urbano/id1093603743?i=1000750039015",
    spotifyUrl: "https://open.spotify.com/episode/451DDoSSZLKTg4IxajSNGw?si=GZupnRnjR3SqpnQnh9RUrg",
    imageUrl: "",
    guestAvatarSeed: "samantaszusterman",
  },
  {
    id: 92,
    title: "Urbanismo, una danza entre ciencia y arte",
    description: "",
    guest: "Ramon Gras Alumà",
    guestRole: "Investigador en Ciencias de la Ciudad y Diseño Urbano, Universidad de Harvard, cofundador de Aretian",
    topics: ["Urbanismo"],
    city: "Boston",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/us/podcast/urbanismo-una-danza-entre-ciencia-y-arte/id1093603743?i=1000671222672",
    spotifyUrl: "https://open.spotify.com/episode/09n34hUOJ0Ar62MTAuApx2?si=t3W-9xvIQFSzE9mZPQ2WnQ",
    imageUrl: "",
    guestAvatarSeed: "ramongrasalum",
  },
  {
    id: 91,
    title: "Silverstone, un evento, una ciudad",
    description: "",
    guest: "Stephane Bazire",
    guestRole: "Director de Sostenibilidad de Silverstone, UK",
    topics: ["Sostenibilidad"],
    city: "Oxford",
    country: "Reino Unido",
    appleUrl: "https://podcasts.apple.com/us/podcast/silverstone-un-evento-una-ciudad/id1093603743?i=1000669990311",
    spotifyUrl: "https://open.spotify.com/episode/4jjB5Qu9crR7j3E1f3tsdV?si=LLkcqiJERaWwV40HN3Z_BA",
    imageUrl: "",
    guestAvatarSeed: "stephanebazire",
  },
  {
    id: 90,
    title: "Mendoza, un oasis urbano",
    description: "",
    guest: "Sebastián Fermani",
    guestRole: "Secretario de Ambiente y Desarrollo Urbano de la Ciudad de Mendoza, Argentina",
    topics: [],
    city: "Mendoza",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/us/podcast/mendoza-un-oasis-urbano/id1093603743?i=1000666946582",
    spotifyUrl: "https://open.spotify.com/episode/4sJBFL63ktIinG7yUl08wK?si=XSKrA6U7Tqq0VVLiGjPhOg",
    imageUrl: "",
    guestAvatarSeed: "sebastinfermani",
  },
  {
    id: 89,
    title: "Impacto local de la acción global de las ciudades",
    description: "",
    guest: "Luz Amparo Medina",
    guestRole: "Consultora, socia de Phare Territorios Globales, Directora Distrital de Relaciones Internacionales de Bogotá (2020-24)",
    topics: ["Ciudades Globales"],
    city: "Bogotá",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/us/podcast/impacto-local-de-la-acci%C3%B3n-global-de-las-ciudades/id1093603743?i=1000666048621",
    spotifyUrl: "https://open.spotify.com/episode/3GEJI67oSU9QANIzyrK1c1?si=8py6PmLIS7OktdF5IJndcQ",
    imageUrl: "/images/ultimo.jpg",
    guestAvatarSeed: "luzamparomedina",
  },
  {
    id: 88,
    title: "De las estrategias a los cambios reales",
    description: "",
    guest: "Xavi Matilla",
    guestRole: "Urbanista, profesor ETSAV-UPC. Arquitecte en Cap de Barcelona (2019-2023)",
    topics: [],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/us/podcast/de-las-estrategias-a-los-cambios-reales/id1093603743?i=1000663958522",
    spotifyUrl: "https://open.spotify.com/episode/2MQlLEIBbRItptpnud4DRY?si=15ad593618824460",
    imageUrl: "",
    guestAvatarSeed: "xavimatilla",
  },
  {
    id: 87,
    title: "Smart City: Modelo Latam",
    description: "",
    guest: "Diana Celis",
    guestRole: "Consultora en Proyectos de TIC, Ciudades y Territorios Inteligentes",
    topics: ["Smart Cities"],
    city: "Bogotá",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/us/podcast/smart-cities-el-modelo-latam/id1093603743?i=1000610928223",
    spotifyUrl: "https://open.spotify.com/episode/6NLH0YWOwvXdT8mhcvX4hf?si=kmEd_ekNRyqMkgtdgbJxPQ",
    imageUrl: "",
    guestAvatarSeed: "dianacelis",
  },
  {
    id: 86,
    title: "Tandil, un modelo inspirador",
    description: "",
    guest: "Pedro Espondaburu",
    guestRole: "Docente Innovación y Desarrollo. Ciencias Económicas Unicen. Tandil, Argentina",
    topics: ["Innovación"],
    city: "Tandil",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/us/podcast/tandil-un-modelo-inspirador/id1093603743?i=1000611751709",
    spotifyUrl: "https://open.spotify.com/episode/0UwM9c3P8ns6iQsy6KXZn4?si=bHJ-BC06TkSoIamY_-lHCw",
    imageUrl: "",
    guestAvatarSeed: "pedroespondaburu",
  },
  {
    id: 85,
    title: "A la escuela en Bicibus!",
    description: "",
    guest: "Mireia Piqueras",
    guestRole: "Vocal del proyecto Bicibus Barcelona",
    topics: ["Movilidad"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000583584745",
    spotifyUrl: "https://open.spotify.com/episode/3gruPqplDXneqNNqnPfne1?si=HRWrVxwwQOm97TnjoO0-PA",
    imageUrl: "",
    guestAvatarSeed: "mireiapiqueras",
  },
  {
    id: 84,
    title: "Ciudades globales en un mundo desglobalizado",
    description: "",
    guest: "Agustí Fernández de Losada",
    guestRole: "Director del programa Ciudades Globales (CIDOB)",
    topics: ["Ciudades Globales"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudades-globales-en-un-mundo-desglobalizado/id1093603743?i=1000571151410",
    spotifyUrl: "https://open.spotify.com/episode/0xMm1L5RS0GTH84bEO5BHb?si=edc7bc4c55f64cd9",
    imageUrl: "",
    guestAvatarSeed: "agustfernndezdelosad",
  },
  {
    id: 83,
    title: "La expansión urbana, una aliada de la biodiversidad.",
    description: "",
    guest: "Nicolás Galarza",
    guestRole: "Viceministro de Ambiente de Colombia",
    topics: ["Sostenibilidad", "Urbanismo", "Equidad"],
    city: "Bogotá",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000567274033",
    spotifyUrl: "https://open.spotify.com/episode/3zYpHdC4okzY0n0eYVeQUQ?si=s-4aEX5JQSOs4ZF3jtHDqQ",
    imageUrl: "",
    guestAvatarSeed: "nicolsgalarza",
  },
  {
    id: 82,
    title: "Pinamar: la reinvención del mar",
    description: "",
    guest: "Martin Yeza",
    guestRole: "Intendente de Pinamar",
    topics: [],
    city: "Pinamar",
    country: "Argentina",
    appleUrl: "https://open.spotify.com/episode/2PpNRwrTz4dhYO9YvdUsPf?si=50316716608f4314",
    spotifyUrl: "https://open.spotify.com/episode/2PpNRwrTz4dhYO9YvdUsPf?si=AgYrB_t-QYW08G1FP5X4JQ",
    imageUrl: "",
    guestAvatarSeed: "martinyeza",
  },
  {
    id: 81,
    title: "Alcaldes de la bicicleta: Madrid",
    description: "",
    guest: "Fernando García",
    guestRole: "Alcalde de la Bici en Madrid",
    topics: ["Movilidad"],
    city: "Madrid",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000558173519",
    spotifyUrl: "https://open.spotify.com/episode/4DAdVvq3CUOKPH5GuXwwHf?si=8ef44125b0f34ae1",
    imageUrl: "",
    guestAvatarSeed: "fernandogarca",
  },
  {
    id: 80,
    title: "El derecho a la ciudad",
    description: "",
    guest: "Lorena Zárate",
    guestRole: "Founder Global Platform for the Right to the City",
    topics: ["Equidad"],
    city: "Ottawa",
    country: "Canada",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000555322146",
    spotifyUrl: "https://open.spotify.com/episode/1588LsqOMi6rWcKJ3iOqBb?si=6eafae54e0d6445c",
    imageUrl: "",
    guestAvatarSeed: "lorenazrate",
  },
  {
    id: 79,
    title: "Desigualdad urbana, un reto del presente",
    description: "",
    guest: "Edgardo Bilsky",
    guestRole: "Director de investigación del Secretariado Mundial de Ciudades y Gobiernos Locales Unidos (CGLU)",
    topics: ["Equidad", "Gobernanza"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/us/podcast/desigualdad-urbana-un-reto-del-presente/id1093603743?i=1000554144936",
    spotifyUrl: "https://open.spotify.com/episode/1foxnB7UI2i8GZURNV7MFL?si=TfVyF7jDS92sOUtg-NoX8A",
    imageUrl: "",
    guestAvatarSeed: "edgardobilsky",
  },
  {
    id: 78,
    title: "Data for public good in metropolitan areas",
    description: "",
    guest: "Sarah Williams",
    guestRole: "Director of the Civic Data Design Lab @ MIT - Author: Data Action",
    topics: ["Datos", "Movilidad", "Urbanismo", "Innovación"],
    city: "New York",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/us/podcast/data-for-public-good-in-metropolitan-areas/id1093603743?i=1000531225243",
    spotifyUrl: "https://open.spotify.com/episode/4QB2GcFmBTeMx2gUapfzOu?si=ba5ea84e7bb24ff1",
    imageUrl: "",
    guestAvatarSeed: "sarahwilliams",
  },
  {
    id: 77,
    title: "Ciudadanía 3.0",
    description: "",
    guest: "Javier Creus",
    guestRole: "Fundador & Director de estrategia de Ideas for Change",
    topics: ["Gobernanza"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/us/podcast/ciudadanos-3-0/id1093603743?i=1000543315413",
    spotifyUrl: "https://open.spotify.com/episode/7nwVHZOwNI9eZZuv26jLxY?si=Vrf-jHONRzKhZNO-aG52BQ",
    imageUrl: "",
    guestAvatarSeed: "javiercreus",
  },
  {
    id: 76,
    title: "Ciudades cuidadoras",
    description: "",
    guest: "Diana Maria Parra Romero",
    guestRole: "Subsecretaria de Politicas de Igualdad de Bogotá",
    topics: [],
    city: "Bogotá",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/us/podcast/bogot%C3%A1-una-ciudad-cuidadora/id1093603743?i=1000535344330",
    spotifyUrl: "https://open.spotify.com/episode/1dqU6pFBnhGbbn0zUihYrg?si=WD1AUwB_RiyI6h-wH0oAbQ",
    imageUrl: "",
    guestAvatarSeed: "dianamariaparraromer",
  },
  {
    id: 75,
    title: "Boti: Una experiencia ciudadana",
    description: "",
    guest: "Agustín Suárez",
    guestRole: "Subsecretario de Ciudad Inteligente",
    topics: ["Smart Cities"],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/us/podcast/boti-una-experiencia-ciudadana/id1093603743?i=1000552154833",
    spotifyUrl: "https://open.spotify.com/episode/6Q7cWs225sNUpUiZZZc5y8?si=lAqsYByDTLypokzJIRkIFg",
    imageUrl: "",
    guestAvatarSeed: "agustnsurez",
  },
  {
    id: 74,
    title: "Buenos Aires: Un elefante ágil",
    description: "",
    guest: "Melisa Breda",
    guestRole: "Subsecretaria de Políticas Públicas basadas en Evidencia, Ciudad de Buenos Aires",
    topics: [],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000527175980",
    spotifyUrl: "https://www.spreaker.com/episode/45482121",
    imageUrl: "",
    guestAvatarSeed: "melisabreda",
  },
  {
    id: 73,
    title: "Urbanistas: integradores en clave espacial",
    description: "",
    guest: "Federico Bervejillo",
    guestRole: "Catedrático de Urbanismo, Ambiente y Paisaje de la Universidad ORT en Uruguay",
    topics: ["Urbanismo"],
    city: "Montevideo",
    country: "Uruguay",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000523565982",
    spotifyUrl: "https://open.spotify.com/episode/2BT8vECE0h3sFQoeiA02Nu?si=Dylg8ID4SPSa_n997DRrOA",
    imageUrl: "",
    guestAvatarSeed: "federicobervejillo",
  },
  {
    id: 72,
    title: "La bici vino para quedarse",
    description: "",
    guest: "Carles Benito",
    guestRole: "Presidente Bicicleta Club de Catalunya",
    topics: ["Movilidad"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/us/podcast/la-bici-vino-para-quedarse/id1093603743?i=1000519737149",
    spotifyUrl: "https://open.spotify.com/episode/43yWoqo8HKAM8SMbLb9nsF?si=WJlkhHv-RVqOkg3G1MOsfg",
    imageUrl: "",
    guestAvatarSeed: "carlesbenito",
  },
  {
    id: 71,
    title: "Metrópolis, el desafío de la escala humana",
    description: "",
    guest: "Octavi de la Varga Mas",
    guestRole: "Metropolis Secretary General",
    topics: ["Movilidad", "Urbanismo"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/us/podcast/metrópolis-el-desaf%C3%ADo-de-la-escala-humana/id1093603743?i=1000516989505",
    spotifyUrl: "https://open.spotify.com/episode/5eD8VV5ZNJDXUUxCQEDyx7?si=j24Lm1W1TXufmd4hw2ymxQ",
    imageUrl: "",
    guestAvatarSeed: "octavidelavargamas",
  },
  {
    id: 70,
    title: "Urbanismo Metropolitano",
    description: "",
    guest: "Gabriel Lanfranchi",
    guestRole: "Director Posgrado Urbanismo Metropolitano, UBA",
    topics: ["Movilidad", "Urbanismo"],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000517839087",
    spotifyUrl: "https://open.spotify.com/episode/6DUhk0MrBQEQsZ1QNRLYtJ?si=5jHI9Y6KRXWctXJw6unaiA",
    imageUrl: "",
    guestAvatarSeed: "gabriellanfranchi",
  },
  {
    id: 69,
    title: "City Prosperity Initiative, UN-Habitat",
    description: "",
    guest: "Luis Herrera Favela",
    guestRole: "City Prosperity Initiative, UN-Habitat",
    topics: [],
    city: "Ottawa",
    country: "Canada",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000507372571",
    spotifyUrl: "https://open.spotify.com/episode/0gj9tmYtCXM1bfpg5ExebE?si=PjOMnAoIQ6yOH-fmplYZ3g",
    imageUrl: "",
    guestAvatarSeed: "luisherrerafavela",
  },
  {
    id: 68,
    title: "El Salvador: el cambio va de la mano de la tecnología",
    description: "",
    guest: "Mónica Taher",
    guestRole: "Technological & Economic International Affairs at Trade & Investments Secretariat - El Salvador’s Government",
    topics: ["Smart Cities"],
    city: "San Salvador",
    country: "El Salvador",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000506524995",
    spotifyUrl: "https://open.spotify.com/episode/5NrpJkrxfpoJBRkimtxtbc?si=5MpniOKfSZSH0K8M4bf8pQ",
    imageUrl: "",
    guestAvatarSeed: "mnicataher",
  },
  {
    id: 67,
    title: "Israel, Start-Up Nation",
    description: "",
    guest: "Sergio Vinitsky",
    guestRole: "Fundador Smart Cities Institute, Israel",
    topics: ["Smart Cities", "Innovación"],
    city: "Tel Aviv",
    country: "Israel",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000503802297",
    spotifyUrl: "https://open.spotify.com/episode/2tI1gLIBuvyMoRIHrZJE0X?si=FGBFrvc8TXOqXwz1hHxZcw",
    imageUrl: "",
    guestAvatarSeed: "sergiovinitsky",
  },
  {
    id: 66,
    title: "Urbanismo y salud: el Covid es un síntoma",
    description: "",
    guest: "Elvis García",
    guestRole: "Doctor en Salud Pública. Harvard University",
    topics: ["Urbanismo", "Salud"],
    city: "Boston",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000482574229",
    spotifyUrl: "https://open.spotify.com/episode/5pn3fgwv4LPehFCk6irDe8?si=LenO0wlxRfyykYfbaF9gfA",
    imageUrl: "",
    guestAvatarSeed: "elvisgarca",
  },
  {
    id: 65,
    title: "La ciudad como proyecto",
    description: "",
    guest: "Jordi Hereu",
    guestRole: "Ex-Alcalde de Barcelona - CEO IdentiCity",
    topics: [],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000407391334",
    spotifyUrl: "https://open.spotify.com/episode/1O9k9RJSb5ndxwJLXeT3ZA?si=A-cteR-7T4us74HRH-EXEQ",
    imageUrl: "",
    guestAvatarSeed: "jordihereu",
  },
  {
    id: 64,
    title: "Privilegios ambientales, una nueva forma de desigualdad",
    description: "",
    guest: "Isabelle Anguelovski",
    guestRole: "Directora del Barcelona Lab for Urban Environmental Justice and Sustainability",
    topics: ["Sostenibilidad", "Equidad", "Innovación"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000452560984",
    spotifyUrl: "https://open.spotify.com/episode/6ER1GtySs7KSiLzFj7kG0g?si=pyZe0zEJQYqDmmjCOqcpPw",
    imageUrl: "",
    guestAvatarSeed: "isabelleanguelovski",
  },
  {
    id: 63,
    title: "Supermanzanas: urbanismo para los ciudadanos",
    description: "",
    guest: "Salvador Rueda",
    guestRole: "Ecólogo urbano. Fundador de la Agencia de Ecología Urbana, Barcelona.",
    topics: ["Sostenibilidad", "Urbanismo"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000426785691",
    spotifyUrl: "https://open.spotify.com/episode/0HsygrTj2vuW8iu5AZQiR4?si=WbIwOpHyR1mfcQHBQXMyBQ",
    imageUrl: "",
    guestAvatarSeed: "salvadorrueda",
  },
  {
    id: 62,
    title: "La simbiosis industrial: nuevo paradigma económico",
    description: "",
    guest: "Verónica Kuchinow",
    guestRole: "CEO SÍMBIOSY. Curadora del Circular Economy European Summit",
    topics: [],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000372447037",
    spotifyUrl: "https://open.spotify.com/episode/1SqjZBVsNh1gHgSQSS218E?si=https://open.spotify.com/episode/1SqjZBVsNh1gHgSQSS218E?si=liIOKFXOQESjtiebWpAAqA",
    imageUrl: "",
    guestAvatarSeed: "vernicakuchinow",
  },
  {
    id: 61,
    title: "Mercados Urbanos: una tradición centenaria en las ciudades",
    description: "",
    guest: "Genis Arnàs",
    guestRole: "Director del servicio de mercados del Instituto Municipal de Mercados de Barcelona",
    topics: ["Espacio Público"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000397479938",
    spotifyUrl: "https://open.spotify.com/episode/3RUMmKQKEXsBbbzJ4mIWKQ?si=7a2_U90ZQLitFCOJz2cbzg",
    imageUrl: "",
    guestAvatarSeed: "genisarns",
  },
  {
    id: 60,
    title: "Conexión de áreas metropolitanas, en bici",
    description: "",
    guest: "Silvia Casorrán",
    guestRole: "Specialist Sustainable Mobility, head of bicycle projects Metropolitan Area of Barcelona",
    topics: ["Movilidad", "Urbanismo"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000412305094",
    spotifyUrl: "https://open.spotify.com/episode/0IqgenJIV0swhwcDiSbiZi?si=vZJP1ZgJQnK1jzJCc1eISg",
    imageUrl: "",
    guestAvatarSeed: "silviacasorrn",
  },
  {
    id: 59,
    title: "Smart Cities: esto va de personas",
    description: "",
    guest: "Josep Ferrer",
    guestRole: "Ex-Director de Smart City y CIO de Barcelona (2012-15), Director Desarrollo Internacional DOXA",
    topics: ["Smart Cities", "Ciudades Globales"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000377535590",
    spotifyUrl: "https://open.spotify.com/episode/3ahQufWmaJKAXNZgudvwda?si=icZ8lrQsTxmi2Mf1Vg1PhA",
    imageUrl: "",
    guestAvatarSeed: "josepferrer",
  },
  {
    id: 58,
    title: "Alimentación, salud y política urbana",
    description: "",
    guest: "Alvaro Porro González",
    guestRole: "Comisionado de Economía Social, Desarrollo Local y Política Alimentaria, Ajuntament de Barcelona",
    topics: ["Salud"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000466763821",
    spotifyUrl: "https://open.spotify.com/episode/5gA3TsP4fCOknlcik2fHTO?si=61FtpWprTU-_Bs8kWODwzA",
    imageUrl: "",
    guestAvatarSeed: "alvaroporrogonzlez",
  },
  {
    id: 57,
    title: "Ciudades Resilientes: estar en forma es la mejor defensa",
    description: "",
    guest: "Esteban León",
    guestRole: "Coordinador del Programa de Resiliencia Urbana de UNHabitat",
    topics: [],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000400805736",
    spotifyUrl: "https://open.spotify.com/episode/4zbEwwemnm2m1L2FZX3Ytg?si=33lpewcHTQq2d2IbK9laAA",
    imageUrl: "",
    guestAvatarSeed: "estebanlen",
  },
  {
    id: 56,
    title: "Smart Cities: una visión global de un concepto en evolución",
    description: "",
    guest: "Pilar Conesa",
    guestRole: "CEO de Anteverti - Curadora del SCEWC Barcelona",
    topics: ["Smart Cities"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000422228583",
    spotifyUrl: "https://open.spotify.com/episode/7lqyI9aKlOdVknTI9bjSkl?si=EDibtLolRrqr9j_jlOAmhQ",
    imageUrl: "",
    guestAvatarSeed: "pilarconesa",
  },
  {
    id: 55,
    title: "Bicicletas públicas",
    description: "",
    guest: "Alvaro Nicolás",
    guestRole: "Asesor de la Regidora de Movilidad del Ayuntamiento de Barcelona",
    topics: ["Movilidad"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000370329334",
    spotifyUrl: "https://open.spotify.com/episode/6rojS0lPtV8xOQ1FLNOa4F?si=3uFJ5TJ6TASUEFQ5BrHELQ",
    imageUrl: "",
    guestAvatarSeed: "alvaronicols",
  },
  {
    id: 54,
    title: "Urbanismo feminista: visibilizando lo cotidiano",
    description: "",
    guest: "Sara Ortiz",
    guestRole: "Urban Planner and Sociologist at Col·lectiu Punt 6 SCCL",
    topics: ["Urbanismo"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000456267503",
    spotifyUrl: "https://open.spotify.com/episode/3agxERa8JqWMt58gnFobAb?si=i1wU8IvgR2yHJuZbyXY-Dg",
    imageUrl: "",
    guestAvatarSeed: "saraortiz",
  },
  {
    id: 53,
    title: "Las ciudades tienen que reinventar la gestión",
    description: "",
    guest: "Luis Gómez",
    guestRole: "Director de Sectores Estratégicos del Ayuntamiento de Barcelona",
    topics: ["Gobernanza"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000430009425",
    spotifyUrl: "https://open.spotify.com/episode/3re7QKcZoKB6sSHqfIpRHK?si=FN30RI_cS0WOcdBI5ac-bg",
    imageUrl: "",
    guestAvatarSeed: "luisgmez",
  },
  {
    id: 52,
    title: "C40: red de ciudades para el desarrollo sostenible",
    description: "",
    guest: "Mariola Panzuela",
    guestRole: "Transport Network Manager | C40 Cities",
    topics: [],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000424333818",
    spotifyUrl: "https://open.spotify.com/episode/5BRuS1OrzozQwNf40S89H7?si=PBKsdRTFTa2mMk-7LkEpiA",
    imageUrl: "",
    guestAvatarSeed: "mariolapanzuela",
  },
  {
    id: 51,
    title: "Bikesharing: dos ruedas, dos modelos",
    description: "",
    guest: "Miguel Rodríguez Planas",
    guestRole: "Manager -Public-Private Sector Research Center (PPSRC) de IESE",
    topics: ["Movilidad"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000444074888",
    spotifyUrl: "https://open.spotify.com/episode/6nkVuCX2uCsT1cofkms5pT?si=hZ8ZubAWQ3axlDM-bo9C9A",
    imageUrl: "",
    guestAvatarSeed: "miguelrodrguezplanas",
  },
  {
    id: 50,
    title: "La ciudad como solución: nueva agenda urbana",
    description: "",
    guest: "Rosa Suriñach",
    guestRole: "Partnerships & Communications ONU Habitat",
    topics: [],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000389710855",
    spotifyUrl: "https://open.spotify.com/episode/11PNrE1JmXGQEparJ4WTJY?si=fP6tlMxcTCmkFebTKjbeFw",
    imageUrl: "",
    guestAvatarSeed: "rosasuriach",
  },
  {
    id: 49,
    title: "Pasado, presente y futuro de las Smart Cities",
    description: "",
    guest: "Ugo Valenti",
    guestRole: "Smart City Expo World Congress Director",
    topics: ["Smart Cities"],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000390366026",
    spotifyUrl: "https://open.spotify.com/episode/6jOdeOCD0bJBDBKq7itjsi?si=NNqb7tNJQaOQVOPvD1hoFA",
    imageUrl: "",
    guestAvatarSeed: "ugovalenti",
  },
  {
    id: 48,
    title: "Siglo XXI, el siglo de las ciudades",
    description: "",
    guest: "CiudadHub",
    guestRole: "Podcast de las Ciudades",
    topics: [],
    city: "Barcelona",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000364882952",
    spotifyUrl: "",
    imageUrl: "",
    guestAvatarSeed: "ciudadhub",
  },
  {
    id: 47,
    title: "Ciudades inclusivas ¿Cómo gestionar la diversidad?",
    description: "",
    guest: "Víctor Pineda",
    guestRole: "President of World ENABLED, Adjunct Professor, Univesity of California at Berkeley",
    topics: ["Equidad"],
    city: "Berkeley",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000414798619",
    spotifyUrl: "https://open.spotify.com/episode/6TGFZTuBCkQs0soRXYp4NJ?si=gIdZVGgeQ0mx72foaPZpRQ",
    imageUrl: "",
    guestAvatarSeed: "vctorpineda",
  },
  {
    id: 46,
    title: "Ciudades: wikipedias urbanas",
    description: "",
    guest: "Manu Fernández",
    guestRole: "Program Coordinator Smart City Expo international events",
    topics: ["Smart Cities"],
    city: "Bilbao",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000380554735",
    spotifyUrl: "https://open.spotify.com/episode/7prTMpO5Corlc5nsrzLYst?si=ddU2OuOxSK2rGuowhwVTVA",
    imageUrl: "",
    guestAvatarSeed: "manufernndez",
  },
  {
    id: 45,
    title: "Bogotá, capital de la bicicleta",
    description: "",
    guest: "David Uniman",
    guestRole: "Gerente de la Bicicleta de la Alcaldía de Bogotá (2015-19)",
    topics: ["Movilidad"],
    city: "Bogotá",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000429341002",
    spotifyUrl: "https://open.spotify.com/episode/5RuMC51tuOEx8QG5stCP29?si=KK-DNvP9SGCe_6eCk7tW5Q",
    imageUrl: "",
    guestAvatarSeed: "daviduniman",
  },
  {
    id: 44,
    title: "Seguridad vial, un tema de salud pública",
    description: "",
    guest: "Johnny López",
    guestRole: "Coordinador de Bogotá del programa Bloomberg para la Seguridad Vial",
    topics: ["Salud"],
    city: "Bogotá",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000368683874",
    spotifyUrl: "https://open.spotify.com/episode/6Uclk36poNNNoMp4iwc2Uq?si=1HpAY4g3RmqNeJyLBEe0rg",
    imageUrl: "",
    guestAvatarSeed: "johnnylpez",
  },
  {
    id: 43,
    title: "Gentrificación en las ciudades",
    description: "",
    guest: "Carlos Hernández",
    guestRole: "Profesor Urbanismo - Universidad Pontificia Javeriana",
    topics: ["Urbanismo"],
    city: "Bogotá",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000382469617",
    spotifyUrl: "https://open.spotify.com/episode/6tNpPIlxQoTBxJ9LGVVhVA?si=V6WKAAMuSnGZo4oBC1hz9A",
    imageUrl: "",
    guestAvatarSeed: "carloshernndez",
  },
  {
    id: 42,
    title: "En movilidad la solución está en compartir",
    description: "",
    guest: "Darío Hidalgo",
    guestRole: "Director Ejecutivo de la Fundación Despacio",
    topics: ["Movilidad"],
    city: "Bogotá",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000433720209",
    spotifyUrl: "https://open.spotify.com/episode/4VobG5HwXT1PuXdpyphWPo?si=OUmaj-43R76MjNQm0L_O_g",
    imageUrl: "",
    guestAvatarSeed: "darohidalgo",
  },
  {
    id: 41,
    title: "GovLab: ¿cómo gobernar a través de la tecnología?",
    description: "",
    guest: "Victoria Alsina",
    guestRole: "Fellow en el Mossavar-Rahmani Center for Business and Government de la Harvard Kennedy School y Profesora de la Universitat Pompeu Fabra",
    topics: ["Smart Cities", "Movilidad", "Innovación"],
    city: "Boston",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000402119482",
    spotifyUrl: "https://open.spotify.com/episode/3PCa5HNkBHcGKYHqpzYyoM?si=3pIPyhfYTkOZ8G7hAcC1yA",
    imageUrl: "",
    guestAvatarSeed: "victoriaalsina",
  },
  {
    id: 40,
    title: "El espacio público, la piel de la democracia",
    description: "",
    guest: "Iván Acevedo",
    guestRole: "Director del Taller Profesional de Arquitectura y Urbanismo del Gobierno de Bucaramanga.",
    topics: ["Urbanismo", "Gobernanza", "Espacio Público"],
    city: "Bucaramanga",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000420078713",
    spotifyUrl: "https://open.spotify.com/episode/071cpQ37kTdMfGmFBVOhvm?si=GvKgapgjR7Sd8Duh-eTqsA",
    imageUrl: "",
    guestAvatarSeed: "ivnacevedo",
  },
  {
    id: 39,
    title: "Nuevos problemas, nuevas competencias",
    description: "",
    guest: "Gabriel Lanfranchi",
    guestRole: "Director Ciudades CIPPEC",
    topics: [],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000443424811",
    spotifyUrl: "https://open.spotify.com/episode/5Rrcu8okMIQF7j10Nc1EDO?si=W4nHSCDOTkqx5e1TiG03gQ",
    imageUrl: "",
    guestAvatarSeed: "gabriellanfranchi",
  },
  {
    id: 38,
    title: "Megalópolis y tribus: dos caras de las ciudades",
    description: "",
    guest: "Fabio Quetglas",
    guestRole: "Abogado, Urbanista, Consultor en desarrollo territorial",
    topics: ["Movilidad"],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000384917427",
    spotifyUrl: "https://open.spotify.com/episode/2bjblHazONIz4iLrPLaMIp?si=-A6ODE7bTeemIKbfMxAhOg",
    imageUrl: "",
    guestAvatarSeed: "fabioquetglas",
  },
  {
    id: 37,
    title: "Gobierno digital para no hacer esperar al ciudadano",
    description: "",
    guest: "Daniel Abadie",
    guestRole: "Ex Subsecretario de Gobierno Digital, Argentina. Consultor Public Digital",
    topics: ["Smart Cities", "Gobernanza"],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000478848610",
    spotifyUrl: "https://open.spotify.com/episode/3cILK06IJXsyPRjICOTJ0B?si=NgOO7THBRnm4Hn-aJ8pGsQ",
    imageUrl: "",
    guestAvatarSeed: "danielabadie",
  },
  {
    id: 36,
    title: "Ciudades y Universidad, una alianza inteligente",
    description: "",
    guest: "Omar Quiroga",
    guestRole: "Director Centro de Ciudades Inteligentes, FCE Universidad de Buenos Aires",
    topics: ["Smart Cities"],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000424604373",
    spotifyUrl: "https://open.spotify.com/episode/1I7W5ngODg3aUa4vzxNthr?si=fOVEAWC6TWquRQpPmtVEyg",
    imageUrl: "",
    guestAvatarSeed: "omarquiroga",
  },
  {
    id: 35,
    title: "Aeropuertos: mini-ciudades",
    description: "",
    guest: "Franco Rinaldi",
    guestRole: "Especialista en aviación. Auditor.",
    topics: [],
    city: "Buenos Aires",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000375136075",
    spotifyUrl: "https://open.spotify.com/episode/0ATjb9vWRwNoTCMCTVj10o?si=dSXpJ7iVSWidmGLqH1PcyQ",
    imageUrl: "",
    guestAvatarSeed: "francorinaldi",
  },
  {
    id: 34,
    title: "Caracas, Venezuela: cómo planificar en medio de la crisis",
    description: "",
    guest: "Zulma Bolívar",
    guestRole: "Presidente en Instituto Metropolitano de Urbanismo Taller Caracas",
    topics: ["Movilidad", "Urbanismo"],
    city: "Caracas",
    country: "Venezuela",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000380054059",
    spotifyUrl: "https://open.spotify.com/episode/3WLObjkec4EcvOq2A1JrgS?si=EeNM16p6QUG-cv513d3r_g",
    imageUrl: "",
    guestAvatarSeed: "zulmabolvar",
  },
  {
    id: 33,
    title: "Caminabilidad, la magia de redescubrir la ciudad",
    description: "",
    guest: "Carolina Huffman",
    guestRole: "Fundadora Urbanismo Vivo",
    topics: ["Urbanismo"],
    city: "Córdoba",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000422759182",
    spotifyUrl: "https://open.spotify.com/episode/3KdrD4SjPAYMuajZTnl5DP?si=hfQIRsYlTP2KQEiIYyvv8w",
    imageUrl: "",
    guestAvatarSeed: "carolinahuffman",
  },
  {
    id: 32,
    title: "Placemaking: transformando espacios públicos en lugares",
    description: "",
    guest: "Guillermo Bernal",
    guestRole: "Coordinador de Placemaking Latinoamérica, Fellow de Project for Public Spaces",
    topics: [],
    city: "Guadalajara",
    country: "México",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000421743124",
    spotifyUrl: "https://open.spotify.com/episode/2V8mOezyRCmssIuBbm1PJa?si=rK1BT3yZQ6qb424qZFt6jg",
    imageUrl: "",
    guestAvatarSeed: "guillermobernal",
  },
  {
    id: 31,
    title: "Parques urbanos: mucho más que el pulmón de las ciudades",
    description: "",
    guest: "Luis Romhan Diez",
    guestRole: "Director general Asociación Nacional de Parques de México",
    topics: ["Espacio Público"],
    city: "Guadalajara",
    country: "México",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000392500408",
    spotifyUrl: "https://open.spotify.com/episode/26eHPCX9WqvXWnOC8U45Sc?si=-0GY4tRZTYGYS5rmquKiQQ",
    imageUrl: "",
    guestAvatarSeed: "luisromhandiez",
  },
  {
    id: 30,
    title: "Lima cómo vamos: los ciudadanos evalúan su ciudad",
    description: "",
    guest: "Patricia Alalta",
    guestRole: "Directora \"Lima Cómo Vamos?\"",
    topics: [],
    city: "Lima",
    country: "Perú",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000394443714",
    spotifyUrl: "https://open.spotify.com/episode/6xbZ22ATYnb0EonTqsFm1J?si=Hsg9xGQJRh-SJWrcE7bqkA",
    imageUrl: "",
    guestAvatarSeed: "patriciaalalta",
  },
  {
    id: 29,
    title: "Medellín ante los desafíos de su éxito",
    description: "",
    guest: "Jorge Pérez Jaramillo",
    guestRole: "Ex-Director de Planeación de Medellín (2012-15) / Lee Kuan Yew World City Prize",
    topics: [],
    city: "Londres",
    country: "Reino Unido",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000384618088",
    spotifyUrl: "https://open.spotify.com/episode/2yhYNSH1ieoxhGtlwQtTw4?si=JVR6JMLLTqS8JkQ-0klzzw",
    imageUrl: "",
    guestAvatarSeed: "jorgeprezjaramillo",
  },
  {
    id: 28,
    title: "Londres: el transporte urbano como actividad vital",
    description: "",
    guest: "Claudia Peñaranda",
    guestRole: "Principal City Planner at Transport for London.",
    topics: ["Movilidad"],
    city: "Londres",
    country: "Reino Unido",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000406474711",
    spotifyUrl: "https://open.spotify.com/episode/6cKohK8PmEcJpDw3vvpeWP?si=HgZSYjKaQoKv8xP3TD7Ivg",
    imageUrl: "",
    guestAvatarSeed: "claudiapearanda",
  },
  {
    id: 27,
    title: "De las ciudades a los territorios: el modelo diamante",
    description: "",
    guest: "Ignacio Alcalde",
    guestRole: "Experto Smart Cities & Territorios Inteligentes",
    topics: ["Smart Cities"],
    city: "Madrid",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000377671173",
    spotifyUrl: "https://open.spotify.com/episode/42YdiNJb7QKxZkiqUNZYFu?si=g6jQxmq0Q_iga6Ujf-VCCw",
    imageUrl: "",
    guestAvatarSeed: "ignacioalcalde",
  },
  {
    id: 26,
    title: "De las autopistas urbanas a las calles peatonales",
    description: "",
    guest: "Carlos Corral",
    guestRole: "Ex subdirector de planificación de movilidad sostenible del Ayuntamiento de Madrid",
    topics: ["Movilidad", "Urbanismo"],
    city: "Madrid",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000446488585",
    spotifyUrl: "https://open.spotify.com/episode/2LzwWYO7grdTJHgICOtw0z?si=LnAlYomMRn-vEoA9k5mccA",
    imageUrl: "",
    guestAvatarSeed: "carloscorral",
  },
  {
    id: 25,
    title: "Reputación, el storydoing-telling de las ciudades",
    description: "",
    guest: "Pau Solanilla Franco",
    guestRole: "Consultor Internacional, autor de La República de la Reputación",
    topics: ["Ciudades Globales"],
    city: "Manresa",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000471285168",
    spotifyUrl: "https://open.spotify.com/episode/3KKZ2VoTRmza7uVEjXov7P?si=3O73Ikn9R3mYcF3XJ1y1xw",
    imageUrl: "",
    guestAvatarSeed: "pausolanillafranco",
  },
  {
    id: 24,
    title: "Liderazgo colaborativo, la clave del desarrollo local",
    description: "",
    guest: "Alain Jorda",
    guestRole: "Experto en Desarrollo Local y Territorial",
    topics: ["Gobernanza", "Innovación"],
    city: "Manresa",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000440101551",
    spotifyUrl: "https://open.spotify.com/episode/3HAwZnmuNX6QNViUJOaEC8?si=0AX-E7PUSlSwQNyH0VbwYg",
    imageUrl: "",
    guestAvatarSeed: "alainjorda",
  },
  {
    id: 23,
    title: "¿Cómo enfrentar la rápida urbanización y el cambio climático?",
    description: "",
    guest: "Ellis Juan",
    guestRole: "Ex-Director Iniciativa Ciudades Emergentes y Sostenibles (BID)",
    topics: ["Sostenibilidad"],
    city: "Miami",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000398690656",
    spotifyUrl: "https://open.spotify.com/episode/6wUIjS1kacDiij6d6sXrHK?si=AVu1JN_vRSSAIqBU5iVE3A",
    imageUrl: "",
    guestAvatarSeed: "ellisjuan",
  },
  {
    id: 22,
    title: "Digitalización de las ciudades",
    description: "",
    guest: "Pedro Uribe",
    guestRole: "Director Regional de Microsoft para Latinoamérica y el Caribe - Latin America & The Caribbean at Microsoft",
    topics: ["Smart Cities"],
    city: "Miami",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000430529167",
    spotifyUrl: "https://open.spotify.com/episode/6yvb4gbZnkGG6nIiliAF9K?si=aQBbU--GSGG3XT4gHKcW-A",
    imageUrl: "",
    guestAvatarSeed: "pedrouribe",
  },
  {
    id: 21,
    title: "Nuevos sistemas de pago para la movilidad urbana",
    description: "",
    guest: "Aida Esteban Millet",
    guestRole: "Senior Director, Urban Mobility and Smart Cities for LAC at Visa",
    topics: ["Smart Cities", "Movilidad"],
    city: "Miami",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000477227309",
    spotifyUrl: "https://open.spotify.com/episode/1EOQ9OagqobqA3vT4yIv63?si=Y5CcM9V-Qo-CTt6VpYA86Q",
    imageUrl: "",
    guestAvatarSeed: "aidaestebanmillet",
  },
  {
    id: 20,
    title: "CiudadesR: cómo devolver el río a las ciudades",
    description: "",
    guest: "Carlos Eduardo Correa",
    guestRole: "Ex Alcalde de Montería y Alto Consejero para las Regiones de la Presidencia de Colombia",
    topics: [],
    city: "Montería",
    country: "Colombia",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000385312004",
    spotifyUrl: "https://open.spotify.com/episode/3g36zBXMxD61yCE6wl1o0j?si=dC7mUsIQRNyGGdTYm8P7Ng",
    imageUrl: "",
    guestAvatarSeed: "carloseduardocorrea",
  },
  {
    id: 19,
    title: "Montevideo: laboratorio urbano",
    description: "",
    guest: "Cristina Zubillaga",
    guestRole: "Directora de Desarrollo Sostenible e Inteligente de la Intendencia de Montevideo",
    topics: ["Innovación"],
    city: "Montevideo",
    country: "Uruguay",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000376736957",
    spotifyUrl: "https://open.spotify.com/episode/3ahQufWmaJKAXNZgudvwda?si=icZ8lrQsTxmi2Mf1Vg1PhA",
    imageUrl: "",
    guestAvatarSeed: "cristinazubillaga",
  },
  {
    id: 18,
    title: "Wonder Innovation Lab: las ciudades como experimento",
    description: "",
    guest: "Carolina Pozo",
    guestRole: "Cofundadora Wonder Lab",
    topics: ["Innovación"],
    city: "New York",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000394443713",
    spotifyUrl: "https://open.spotify.com/episode/5N0pcHdk8tFfBw7H4zzeUJ?si=BIsCy5g6QTKXTQTmdIGG4Q",
    imageUrl: "",
    guestAvatarSeed: "carolinapozo",
  },
  {
    id: 17,
    title: "Economía popular, ciudades y tecnología",
    description: "",
    guest: "Mercedes Bidart",
    guestRole: "Fellow NYC Mayor's Office, MIT Master in City Planning, QUIPU co-founder",
    topics: ["Smart Cities"],
    city: "New York",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000448958913",
    spotifyUrl: "https://open.spotify.com/episode/0aGXhj45fTDM6vvlGdWV1r?si=4reqQ5IhT0yrqCe8owGwRQ",
    imageUrl: "",
    guestAvatarSeed: "mercedesbidart",
  },
  {
    id: 16,
    title: "Social Bicycle: movilidad medida en byts",
    description: "",
    guest: "Daniel Treviño",
    guestRole: "Project Manager de Social Bicycle",
    topics: ["Movilidad"],
    city: "New York",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000371747782",
    spotifyUrl: "https://open.spotify.com/episode/4sSizDinbkUane7Hruy2SY?si=xUzuy2CvTlOt4gS46ld7fg",
    imageUrl: "",
    guestAvatarSeed: "danieltrevio",
  },
  {
    id: 15,
    title: "NYC, el bus también existe!",
    description: "",
    guest: "Julián Bautista Rojas",
    guestRole: "Planificador Principal de Transporte en MTA Bus Company - Nueva York",
    topics: ["Movilidad"],
    city: "New York",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000420668860",
    spotifyUrl: "https://open.spotify.com/episode/3wxJHepvp7BvmpgKsVkkXM?si=iWfRYLONSKiSGiHarYm4hg",
    imageUrl: "",
    guestAvatarSeed: "julinbautistarojas",
  },
  {
    id: 14,
    title: "Vehículos eléctricos: pasado, presente y futuro",
    description: "",
    guest: "CiudadHub",
    guestRole: "Podcast de las Ciudades",
    topics: ["Movilidad"],
    city: "Ottawa",
    country: "Canada",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000368131447",
    spotifyUrl: "",
    imageUrl: "",
    guestAvatarSeed: "ciudadhub",
  },
  {
    id: 13,
    title: "Portland: una atípica ciudad estadounidense",
    description: "",
    guest: "Mauricio Leclerc",
    guestRole: "Transportation Planning Section Manager - Portland, Oregon",
    topics: [],
    city: "Portland",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000403022231",
    spotifyUrl: "https://open.spotify.com/episode/5x0oBfs58K3rphi0ZVHam5?si=5DBx0eUoRiK_G-8HGNiEww",
    imageUrl: "",
    guestAvatarSeed: "mauricioleclerc",
  },
  {
    id: 12,
    title: "Hacker activismo urbano",
    description: "",
    guest: "Leonardo Brawl",
    guestRole: "TransLAB.URB - Co-Founder",
    topics: ["Innovación"],
    city: "Porto Alegre",
    country: "Brasil",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000423195098",
    spotifyUrl: "https://open.spotify.com/episode/0i2DkzeKNj6S9N59M5ldYd?si=pV091p7mQK68AJhvUFhY2A",
    imageUrl: "",
    guestAvatarSeed: "leonardobrawl",
  },
  {
    id: 11,
    title: "SmartCity Expo Latam: la experiencia latinoamericana",
    description: "",
    guest: "Manuel Redondo",
    guestRole: "Director Smart City Expo Latam",
    topics: ["Smart Cities"],
    city: "Puebla",
    country: "México",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000395387019",
    spotifyUrl: "https://open.spotify.com/episode/3CGGU8qPX3KB1g0iZrXAzO?si=eITVmriLSgCxWT0031c-8A",
    imageUrl: "",
    guestAvatarSeed: "manuelredondo",
  },
  {
    id: 10,
    title: "La implementación de la nueva agenda urbana - WUF9 Kuala Lumpur",
    description: "",
    guest: "Elkin Velasquez",
    guestRole: "Director ONUHabitat Latinoamérica y el Caribe",
    topics: [],
    city: "Rio de Janeiro",
    country: "Brasil",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000404429488",
    spotifyUrl: "https://open.spotify.com/episode/3LKvaPrpOR5x7wuAZCGQdp?si=4lhxti-eQ2qqBu74AoLxUg",
    imageUrl: "",
    guestAvatarSeed: "elkinvelasquez",
  },
  {
    id: 9,
    title: "El Malestar en las ciudades",
    description: "",
    guest: "Elkin Velasquez",
    guestRole: "Director ONUHabitat Latinoamérica y el Caribe",
    topics: [],
    city: "Rio de Janeiro",
    country: "Brasil",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000460870405",
    spotifyUrl: "https://open.spotify.com/episode/54kxLwjThkwS4kI9UeHhzx?si=T6REzC3NQD2j-HEVYyuP_Q",
    imageUrl: "",
    guestAvatarSeed: "elkinvelasquez",
  },
  {
    id: 8,
    title: "Ciudades 880, para los de 8 y los de 80",
    description: "",
    guest: "Guillermo Peñalosa",
    guestRole: "Fundador y presidente de Ciudades 8 80",
    topics: [],
    city: "Toronto",
    country: "Canada",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000408860992",
    spotifyUrl: "https://open.spotify.com/episode/77oQtFWpwU8ybMPLY3r7mk?si=PMwOgL1XQ522FpFhpFq0Lg",
    imageUrl: "",
    guestAvatarSeed: "guillermopealosa",
  },
  {
    id: 7,
    title: "Las ciudades son \"cosa de niños\"",
    description: "",
    guest: "Verónica Mansilla",
    guestRole: "Arquitecta fundadora del Estudio Trecediecinueve",
    topics: [],
    city: "Tucumán",
    country: "Argentina",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000425048218",
    spotifyUrl: "https://open.spotify.com/episode/0kLbHUKsjhfBfziEuwFlDw?si=F1Dyd9UsTxSC5uhj4fN2tA",
    imageUrl: "",
    guestAvatarSeed: "vernicamansilla",
  },
  {
    id: 6,
    title: "En las ciudades, experimentar no es improvisar",
    description: "",
    guest: "Jordi Honey-Roses",
    guestRole: "Assistant Professor at the School of Community and Regional Planning, University of British Columbia",
    topics: [],
    city: "Vancouver",
    country: "Canada",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000450957597",
    spotifyUrl: "https://open.spotify.com/episode/6S9r9XB3luPtZdVcb29yn3?si=vpw7_Of2TYy70b2dzre_Aw",
    imageUrl: "",
    guestAvatarSeed: "jordihoneyroses",
  },
  {
    id: 5,
    title: "Waterproofing data",
    description: "",
    guest: "Joao Porto de Albuquereque",
    guestRole: "Director, Institute for Global Sustainable Development, University of Warwick",
    topics: ["Datos"],
    city: "Warwick",
    country: "Reino Unido",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000468470173",
    spotifyUrl: "https://open.spotify.com/episode/1tO3ZccyHfDhGwiaHgDPfy?si=MspJAZTjQJK5sWqknL5okw",
    imageUrl: "",
    guestAvatarSeed: "joaoportodealbuquere",
  },
  {
    id: 4,
    title: "Big data y urbanismo: lo importante son las preguntas",
    description: "",
    guest: "Nancy Lozano",
    guestRole: "Economista Senior Banco Mundial",
    topics: ["Datos", "Urbanismo"],
    city: "Washington",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000465633344",
    spotifyUrl: "https://open.spotify.com/episode/0nSCEfBLhdGEIwqYejFc7X?si=1JkctXS2Rn28h9VYkaA2mQ",
    imageUrl: "",
    guestAvatarSeed: "nancylozano",
  },
  {
    id: 3,
    title: "Ir más despacio para llegar antes",
    description: "",
    guest: "Carlos Pardo",
    guestRole: "Senior Manager - Pilots at NUMO -New Urban Mobility Alliance",
    topics: ["Movilidad"],
    city: "Washington",
    country: "EEUU",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000440992766",
    spotifyUrl: "https://open.spotify.com/episode/4cVnj89Sz5k6GMNvy9seXH?si=_ECPF-daSACE1l_np5RbrQ",
    imageUrl: "",
    guestAvatarSeed: "carlospardo",
  },
  {
    id: 2,
    title: "Del transporte público colectivo a las plataformas de movilidad",
    description: "",
    guest: "Juan Ortiz",
    guestRole: "Director del Consorcio de Transportes de Zaragoza",
    topics: ["Movilidad"],
    city: "Zaragoza",
    country: "España",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000391320970",
    spotifyUrl: "https://open.spotify.com/episode/121bmQ3T8lnOp85lFAeQre?si=9fERZqT5QV2d_qSI3NDG_A",
    imageUrl: "",
    guestAvatarSeed: "juanortiz",
  },
  {
    id: 1,
    title: "CDMX: escuchar y compartir, una estrategia de inserción internacional",
    description: "",
    guest: "Mariana Flores Mayen",
    guestRole: "Directora Ejecutiva de Representación Institucional CDMX",
    topics: ["Ciudades Globales"],
    city: "Ottawa",
    country: "Canada",
    appleUrl: "https://podcasts.apple.com/ca/podcast/ciudad-hubs-tracks/id1093603743?i=1000475488505",
    spotifyUrl: "https://open.spotify.com/episode/10TOlsvfqhHOkCL9aWssPs?si=zkfaJEmIRjC3qXHM_euwQQ",
    imageUrl: "",
    guestAvatarSeed: "marianafloresmayen",
  },
]

export const allTopics: TopicStat[] = [
  { name: "Movilidad", count: 23 },
  { name: "Smart Cities", count: 17 },
  { name: "Urbanismo", count: 16 },
  { name: "Innovación", count: 11 },
  { name: "Gobernanza", count: 6 },
  { name: "Sostenibilidad", count: 5 },
  { name: "Ciudades Globales", count: 5 },
  { name: "Equidad", count: 5 },
  { name: "Salud", count: 4 },
  { name: "Datos", count: 3 },
  { name: "Espacio Público", count: 3 },
]

export const allGuests = episodes.map(ep => ({
  name: ep.guest,
  role: ep.guestRole,
  city: ep.city,
  topics: ep.topics,
  episodeId: ep.id,
  episodeTitle: ep.title,
  appleUrl: ep.appleUrl,
  spotifyUrl: ep.spotifyUrl,
  guestAvatarSeed: ep.guestAvatarSeed,
}))
